// packages/angular/src/components/radio-group/radio-group-item.component.ts
import { CommonModule } from '@angular/common';
import { Component, ElementRef, HostListener, Input, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'button[pui-radio-group-item]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg
      *ngIf="checked"
      class="indicator"
      width="15"
      height="15"
      viewBox="0 0 15 15"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle cx="7.5" cy="7.5" r="3.3" fill="currentColor"></circle>
    </svg>
    <input
      type="hidden"
      [attr.id]="elementRef.nativeElement.id"
      [attr.name]="elementRef.nativeElement.name"
      [value]="value"
    />
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 1rem;
        height: 1rem;
        border-radius: 50%;
        border: 1px solid var(--color-primary);
        box-shadow: var(--box-shadow-default);
        cursor: pointer;
        transition: background-color 0.2s;
        outline: none;
        padding: 0;
      }

      :host:focus-visible {
        box-shadow: 0 0 0 1px var(--color-ring);
      }

      :host[aria-checked='true'] {
        background-color: var(--color-primary);
        color: var(--color-primary-fg);
      }

      :host:disabled {
        cursor: not-allowed;
        opacity: 0.5;
      }

      :host svg {
        width: 100%;
        height: 100%;
      }
    `,
  ],
  host: {
    type: 'button',
    role: 'radio',
    'data-testid': 'pui-radio-group-item',
    '[attr.aria-checked]': 'checked',
    '[attr.data-state]': 'checked ? "checked" : "unchecked"',
  },
})
export class RadioGroupItemComponent {
  @Input() checked = false;
  @Input() value: string | number | null = null;
  @Output() valueSelect = new EventEmitter<string | number | null>();

  constructor(public elementRef: ElementRef) {}

  @HostListener('click')
  toggleCheck() {
    if (!this.elementRef.nativeElement.disabled) {
      this.valueSelect.emit(this.value);
    }
  }
}

// packages/vue/src/components/radio-group/radio-group-item.vue
<script setup lang="ts">
import { computed } from "vue";
import { RadioGroupItem, RadioGroupItemIndicator } from "reka-ui";
import { cva, type VariantProps } from "class-variance-authority";
import { Check } from "lucide-vue-next";

const radioGroupItemVariants = cva("q-radio-group-item", {
  variants: {},
  defaultVariants: {},
});

export type RadioGroupItemVariants = VariantProps<typeof radioGroupItemVariants>;

export interface RadioGroupItemProps {
  value: string;
  disabled?: boolean;
  asChild?: boolean;
}

const props = withDefaults(defineProps<RadioGroupItemProps>(), {
  disabled: false,
  asChild: false,
});

const classes = computed(() => {
  return radioGroupItemVariants({});
});
</script>

<template>
  <RadioGroupItem
    :value="value"
    :disabled="disabled"
    :as-child="asChild"
    :class="classes"
    v-bind="$attrs"
  >
    <slot />
    <RadioGroupItemIndicator :class="['q-radio-group-item-indicator']">
      <Check :size="14" />
    </RadioGroupItemIndicator>
  </RadioGroupItem>
</template>

<style scoped>
.q-radio-group-item {
  aspect-ratio: 1 / 1;
  height: var(--spacing-4);
  width: var(--spacing-4);
  border-radius: var(--border-radius-full);
  border: var(--border-width-default) solid var(--color-primary);
  color: var(--color-primary);
  box-shadow: var(--box-shadow-sm);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  outline: none;
  padding: 0;
  background-color: transparent;
  transition: background-color 0.2s;
}

.q-radio-group-item:focus {
  outline: none;
}

.q-radio-group-item:focus-visible {
  box-shadow: 0 0 0 1px var(--color-ring);
}

.q-radio-group-item[data-state="checked"] {
  background-color: var(--color-primary);
  color: var(--color-primary-fg);
}

.q-radio-group-item:disabled,
.q-radio-group-item[data-disabled] {
  cursor: not-allowed;
  opacity: 0.5;
}

.q-radio-group-item-indicator {
  display: flex;
  align-items: center;
  justify-content: center;
  color: currentColor;
}
</style>
