// packages/vue/src/components/accordion/accordion-item.vue
<script setup lang="ts">
import { AccordionItem as RekaAccordionItem } from 'reka-ui'

export interface AccordionItemProps {
  value: string
  disabled?: boolean
}

const props = withDefaults(defineProps<AccordionItemProps>(), {
  disabled: false
})
</script>

<template>
  <RekaAccordionItem
    :value="value"
    :disabled="disabled"
    :class="['q-accordion-item']"
    v-bind="$attrs"
  >
    <slot />
  </RekaAccordionItem>
</template>

<style scoped>
.q-accordion-item {
  display: flex;
  flex-direction: column;
  border-bottom: var(--border-width-default) solid var(--color-border);
}
</style>

// packages/angular/src/components/accordion/accordion-item.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: '[qui-accordion-item]',
  host: {
    'data-testid': 'qui-accordion-item',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        border-bottom: 1px solid var(--color-border);
      }
    `,
  ],
  standalone: true,
})
export class AccordionItemComponent {
  @Output() toggle = new EventEmitter<void>();
  isOpen = false;

  toggleOpen() {
    this.isOpen = !this.isOpen;
    this.toggle.emit();
  }
}
