// packages/angular/src/components/tag-input/tag-input.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from '../button/button.component';
import { InputComponent } from '../input/input.component';
import { TagComponent } from '../tag/tag.component';

@Component({
  selector: '[qui-tag-input]',
  standalone: true,
  host: {
    role: 'textbox',
  },
  imports: [
    CommonModule,
    FormsModule,
    ButtonComponent,
    TagComponent,
    InputComponent,
  ],
  template: `
    <div
      class="tag-input-container"
      data-testid="qui-tag-input"
      (click)="handleClick()"
      (keydown)="handleKeydown($event)"
      tabindex="0"
    >
      <input
        #tagInput
        qui-input
        data-testid="qui-tag-input-input"
        type="text"
        placeholder="Enter tags (comma-separated)..."
        [(ngModel)]="inputValue"
        (keydown)="handleInputKeyDown($event)"
        (blur)="handleInputBlur()"
        class="tag-input"
        aria-label="Enter tags"
      />
      <input
        type="hidden"
        [attr.name]="name"
        [attr.id]="elementRef.nativeElement.id"
        [ngModel]="tags"
      />

      <div
        *ngIf="tags.length > 0"
        class="tags-container"
        role="list"
        aria-live="polite"
      >
        <div
          qui-tag
          size="sm"
          data-testid="qui-tag-input-tag"
          *ngFor="let tag of tags; let i = index"
          class="tag"
          role="listitem"
        >
          <span>{{ tag }}</span>
          <button
            qui-button
            size="icon"
            (click)="removeTag(i)"
            class="remove-tag"
            [attr.aria-label]="'Remove tag ' + tag"
          >
            &times;
          </button>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .tag-input-container {
        border: var(--border-width-default) solid var(--color-border);
        border-radius: var(--border-radius-md);
        background-color: var(--color-background);
        padding: var(--spacing-2);
        display: flex;
        flex-flow: column wrap;
        justify-content: center;
      }

      .tag-input {
        border: none;
        outline: none;
        flex: 1;
        background-color: transparent;
      }

      .tag-input.size--md {
        font-size: var(--font-size-base);
        padding: var(--spacing-2) 0;
      }

      .tags-container {
        display: flex;
        flex-wrap: wrap;
        gap: var(--spacing-2);
        max-height: 100px;
        overflow-y: auto;
      }

      .tag {
        justify-content: space-between;
        width: fit-content;
        max-width: 100%;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }

      .tag span {
        flex: 1;
      }

      .remove-tag {
        background: none;
        border: none;
        cursor: pointer;
      }

      .remove-tag.size--icon {
        width: var(--spacing-4);
        height: var(--spacing-4);
      }
    `,
  ],
})
export class TagInputComponent {
  @Input() name?: string;
  @Input() tags: string[] = [];
  @Output() tagsChange = new EventEmitter<string[]>();
  @ViewChild('tagInput') tagInput!: ElementRef<HTMLInputElement>;

  inputValue = '';

  constructor(protected elementRef: ElementRef) {}

  handleInputKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      event.preventDefault();
      this.addTags(this.inputValue);
    } else if (event.key === 'Backspace' && !this.inputValue) {
      this.removeTag(this.tags.length - 1);
    }
  }

  handleInputBlur() {
    if (this.inputValue) {
      this.addTags(this.inputValue);
    }
  }

  addTags(input: string) {
    const newTags = input
      .split(',')
      .map((tag) => tag.trim())
      .filter((tag) => tag && !this.tags.includes(tag));

    if (newTags.length > 0) {
      this.tags = [...this.tags, ...newTags];
      this.inputValue = '';
      this.tagsChange.emit(this.tags);
    }
  }

  removeTag(index: number) {
    this.tags.splice(index, 1);
    this.tagsChange.emit(this.tags);
  }

  focusInput() {
    this.tagInput.nativeElement.focus();
  }

  handleClick() {
    this.tagInput.nativeElement.focus();
  }

  handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.tagInput.nativeElement.focus();
    }
  }
}

// packages/vue/src/components/tag-input/tag-input.vue
<script setup lang="ts">
import { computed, ref, nextTick } from "vue";
import TagComponent from "@/components/tag/tag.vue";
import InputComponent from "@/components/input/input.vue";
import ButtonComponent from "@/components/button/button.vue";
import { X } from "lucide-vue-next";

export interface TagInputProps {
  name?: string;
  modelValue?: string[];
  placeholder?: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<TagInputProps>(), {
  modelValue: () => [],
  placeholder: "Enter tags (comma-separated)...",
  disabled: false,
});

const emit = defineEmits<{
  "update:modelValue": [value: string[]];
}>();

const inputValue = ref("");
const tagInputRef = ref<InstanceType<typeof InputComponent> | null>(null);

const tags = computed({
  get: () => props.modelValue || [],
  set: (value) => emit("update:modelValue", value),
});

const handleInputKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Enter") {
    event.preventDefault();
    addTags(inputValue.value);
  } else if (event.key === "Backspace" && !inputValue.value && tags.value.length > 0) {
    removeTag(tags.value.length - 1);
  }
};

const handleInputBlur = () => {
  if (inputValue.value) {
    addTags(inputValue.value);
  }
};

const addTags = (input: string) => {
  const newTags = input
    .split(",")
    .map((tag) => tag.trim())
    .filter((tag) => tag && !tags.value.includes(tag));

  if (newTags.length > 0) {
    tags.value = [...tags.value, ...newTags];
    inputValue.value = "";
  }
};

const removeTag = (index: number) => {
  const newTags = [...tags.value];
  newTags.splice(index, 1);
  tags.value = newTags;
};

const focusInput = async () => {
  await nextTick();
  // Focus the input element
  if (tagInputRef.value) {
    const inputElement = tagInputRef.value.$el as HTMLInputElement;
    if (inputElement && inputElement.focus) {
      inputElement.focus();
    }
  }
};

const handleClick = () => {
  focusInput();
};

const handleKeydown = (event: KeyboardEvent) => {
  if (event.key === "Enter") {
    focusInput();
  }
};
</script>

<template>
  <div
    class="tag-input-container"
    role="textbox"
    data-testid="qui-tag-input"
    @click="handleClick"
    @keydown="handleKeydown"
    tabindex="0"
  >
    <InputComponent
      ref="tagInputRef"
      v-model="inputValue"
      data-testid="qui-tag-input-input"
      type="text"
      :placeholder="placeholder"
      :disabled="disabled"
      class="tag-input"
      aria-label="Enter tags"
      @keydown="handleInputKeyDown"
      @blur="handleInputBlur"
    />

    <input
      v-if="name"
      type="hidden"
      :name="name"
      :value="tags.join(',')"
    />

    <div
      v-if="tags.length > 0"
      class="tags-container"
      role="list"
      aria-live="polite"
    >
      <TagComponent
        v-for="(tag, index) in tags"
        :key="index"
        size="sm"
        data-testid="qui-tag-input-tag"
        class="tag"
        role="listitem"
      >
        <span>{{ tag }}</span>
        <ButtonComponent
          size="icon"
          variant="ghost"
          class="remove-tag"
          :aria-label="`Remove tag ${tag}`"
          @click.stop="removeTag(index)"
        >
          <X :size="16" />
        </ButtonComponent>
      </TagComponent>
    </div>
  </div>
</template>

<style scoped>
.tag-input-container {
  border: var(--border-width-default) solid var(--color-border);
  border-radius: var(--border-radius-md);
  background-color: var(--color-background);
  padding: var(--spacing-2);
  display: flex;
  flex-flow: column wrap;
  justify-content: center;
  min-height: var(--spacing-10);
}

.tag-input-container:focus-visible {
  outline: none;
  border-color: var(--color-ring);
  box-shadow:
    0 0 0 2px var(--color-ring),
    0 0 0 4px var(--color-background);
}

.tag-input {
  border: none;
  outline: none;
  flex: 1;
  background-color: transparent;
  box-shadow: none;
}

.tag-input:focus-visible {
  box-shadow: none;
}

.tag-input.size--md {
  font-size: var(--font-size-base);
  padding: var(--spacing-2) 0;
}

.tags-container {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-2);
  max-height: 100px;
  overflow-y: auto;
  margin-top: var(--spacing-2);
}

.tag {
  justify-content: space-between;
  width: fit-content;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.tag span {
  flex: 1;
}

.remove-tag {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
  margin-left: var(--spacing-1);
}

.remove-tag.size--icon {
  width: var(--spacing-4);
  height: var(--spacing-4);
}
</style>
