// packages/vue/src/components/toast/toast.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'
import { cva, type VariantProps } from 'class-variance-authority'

const toastVariants = cva('q-toast', {
  variants: {
    variant: {
      default: 'variant--default',
      destructive: 'variant--destructive'
    }
  },
  defaultVariants: {
    variant: 'default'
  }
})

export type ToastVariants = VariantProps<typeof toastVariants>

export interface ToastProps {
  variant?: ToastVariants['variant']
  asChild?: boolean
}

const props = withDefaults(defineProps<ToastProps>(), {
  variant: 'default',
  asChild: false
})

const classes = computed(() => {
  return toastVariants({
    variant: props.variant
  })
})
</script>

<template>
  <Primitive
    :as-child="asChild"
    :class="classes"
    data-testid="qui-toast"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: var(--spacing-2);
  box-sizing: border-box;
  padding: var(--spacing-4);
  padding-right: var(--spacing-8);
  border-radius: var(--border-radius-md);
  box-shadow: var(--box-shadow-lg);
  transition: all 0.3s;
}

.variant--default {
  background-color: var(--color-background);
  color: var(--color-background-fg);
}

.variant--destructive {
  background-color: var(--color-danger);
  color: var(--color-danger-fg);
}
</style>

// packages/angular/src/components/toast/toast.component.ts
import { Component, Input } from '@angular/core';

export type ToastVariants = {
  variant: 'default' | 'destructive';
};

@Component({
  selector: 'qui-toast',
  standalone: true,
  host: {
    '[class]': 'getClassList()',
    'data-testid': 'qui-toast',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        position: relative;
        display: flex;
        flex-direction: column;
        gap: var(--spacing-2);
        box-sizing: border-box;
        padding: var(--spacing-4);
        padding-right: var(--spacing-8);
        border-radius: var(--border-radius-md);
        box-shadow: var(--box-shadow-lg);
        transition: all 0.3s;
      }

      :host-context(.variant--default) {
        background-color: var(--color-background);
        color: var(--color-background-fg);
      }

      :host-context(.variant--destructive) {
        background-color: var(--color-danger);
        color: var(--color-danger-fg);
      }
    `,
  ],
})
export class ToastComponent {
  @Input() variant: ToastVariants['variant'] = 'default';

  getClassList() {
    return `variant--${this.variant}`;
  }
}
