// packages/angular/src/components/star-rating/star-rating.component.ts
import { Component, Input } from '@angular/core';
import { IconStarComponent } from '../../icons';
import { CommonModule } from '@angular/common';

@Component({
  selector: '[qui-star-rating]',
  imports: [CommonModule, IconStarComponent],
  standalone: true,
  host: {
    'data-testid': 'star-rating',
  },
  template: `
    <i
      data-testid="star-rating__star"
      qui-icon
      name="star"
      [ngClass]="getStarClassList(star)"
      *ngFor="let star of total"
    >
    </i>
  `,
  styles: [
    `
      :host {
        display: flex;
        align-items: center;
        gap: var(--spacing-1);
      }

      .star {
        width: var(--spacing-4);
        height: var(--spacing-4);
      }

      .star.variant--filled {
        fill: var(--color-yellow-500);
      }

      .star.variant--unfilled {
        fill: var(--color-gray-300);
      }
    `,
  ],
})
export class StarRatingComponent {
  @Input() rating = 0;
  @Input() stars = 5;

  get total() {
    return Array.from({ length: this.stars }, (_, i) => i + 1);
  }

  getStarClassList(index: number) {
    return {
      star: true,
      [`variant--filled`]: index <= this.rating,
      [`variant--unfilled`]: index > this.rating,
    };
  }
}

// packages/vue/src/components/star-rating/star-rating.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";
import { cva, type VariantProps } from "class-variance-authority";

const starVariants = cva("q-star-rating-star", {
  variants: {
    filled: {
      true: "variant--filled",
      false: "variant--unfilled",
    },
  },
  defaultVariants: {
    filled: false,
  },
});

export type StarRatingVariants = VariantProps<typeof starVariants>;

export interface StarRatingProps {
  rating?: number;
  stars?: number;
  asChild?: boolean;
}

const props = withDefaults(defineProps<StarRatingProps>(), {
  rating: 0,
  stars: 5,
  asChild: false,
});

const totalStars = computed(() => {
  return Array.from({ length: props.stars }, (_, i) => i + 1);
});

const isStarFilled = (index: number) => {
  return index <= props.rating;
};

const getStarClasses = (index: number) => {
  return starVariants({
    filled: isStarFilled(index),
  });
};
</script>

<template>
  <Primitive
    :as="asChild ? undefined : 'div'"
    :as-child="asChild"
    class="q-star-rating"
    data-testid="qui-star-rating"
    v-bind="$attrs"
  >
    <svg
      v-for="star in totalStars"
      :key="star"
      :class="getStarClasses(star)"
      viewBox="0 0 20 20"
      fill="currentColor"
      data-testid="qui-star-rating-star"
      aria-hidden="true"
    >
      <path
        fill-rule="evenodd"
        d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z"
        clip-rule="evenodd"
      />
    </svg>
  </Primitive>
</template>

<style scoped>
.q-star-rating {
  display: flex;
  align-items: center;
  gap: var(--spacing-1);
}

.q-star-rating-star {
  width: var(--spacing-4);
  height: var(--spacing-4);
  flex-shrink: 0;
}

.q-star-rating-star.variant--filled {
  fill: var(--color-yellow-500);
  color: var(--color-yellow-500);
}

.q-star-rating-star.variant--unfilled {
  fill: var(--color-gray-300);
  color: var(--color-gray-300);
}
</style>
