// packages/vue/src/components/reel/reel.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface ReelProps {
  asChild?: boolean
}

const props = withDefaults(defineProps<ReelProps>(), {
  asChild: false
})
</script>

<template>
  <Primitive
    :as="'div'"
    :as-child="asChild"
    :class="['q-reel']"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-reel {
  position: relative;
  display: flex;
  overflow: hidden;
}
</style>

// packages/angular/src/components/reel/reel.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[pui-reel]',
  template: ` <ng-content></ng-content> `,
  standalone: true,
  host: {
    'data-testid': 'pui-reel',
  },
  styles: [
    `
      :host {
        position: relative;
        display: flex;
        overflow: hidden;
      }
    `,
  ],
})
export class ReelComponent {}
