// packages/vue/src/components/spotlight-gallery/spotlight-gallery-content.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'
</script>

<template>
  <Primitive
    as="div"
    :class="['q-spotlight-gallery-content']"
    data-testid="qui-spotlight-gallery-content"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-spotlight-gallery-content {
  width: 100%;
  aspect-ratio: 1;
}
</style>

// packages/angular/src/components/spotlight-gallery/spotlight-gallery-content.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'div[qui-spotlight-gallery-content]',
  standalone: true,
  imports: [CommonModule],
  host: {
    'data-testid': 'qui-spotlight-gallery-content',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        width: 100%;
        aspect-ratio: 1;
      }
    `,
  ],
})
export class SpotlightGalleryContentComponent {}
