// packages/angular/src/components/toggle/toggle.component.ts
import { CommonModule } from '@angular/common';
import { Component, HostListener, Input, Output, EventEmitter } from '@angular/core';

export type ToggleVariants = {
  variant: 'default' | 'outline';
  size: 'sm' | 'md' | 'lg';
};

@Component({
  selector: 'button[pui-toggle]',
  standalone: true,
  imports: [CommonModule],
  host: {
    '[class]': 'getClassList()',
    'data-testid': 'pui-toggle',
    '[attr.aria-pressed]': 'selected',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: var(--spacing-2);
        border: 0;
        margin: 0;
        border-radius: var(--border-radius-md);
        font-size: var(--font-size-sm);
        font-weight: var(--font-weight-medium);
        transition: colors 0.3s;
        outline: none;

        &:focus-visible {
          box-shadow:
            0 0 0 2px var(--color-ring),
            0 0 0 4px var(--color-background);
        }

        &:not(:disabled) {
          cursor: pointer;
        }

        &:disabled {
          pointer-events: none;
          opacity: 0.5;
        }
      }

      :host(.variant--default) {
        background-color: var(--color-card);
        color: var(--color-card-fg);
        box-shadow: var(--box-shadow-sm);
      }

      :host(.variant--outline) {
        border: 1px solid var(--color-border);
        background-color: transparent;

        &:hover {
          background-color: var(--color-primary);
          color: var(--color-primary-fg);
        }
      }

      :host(.size--sm) {
        height: var(--spacing-8);
        padding: var(--spacing-1-5);
      }

      :host(.size--md) {
        height: var(--spacing-9);
        padding: var(--spacing-2);
      }

      :host(.size--lg) {
        height: var(--spacing-10);
        padding: var(--spacing-2-5);
      }

      :host([aria-pressed='true']) {
        background-color: var(--color-primary);
        color: var(--color-primary-fg);
      }
    `,
  ],
})
export class ToggleComponent {
  @Input() variant: ToggleVariants['variant'] = 'default';
  @Input() size: ToggleVariants['size'] = 'md';
  @Input() selected = false;
  @Input() value = '';

  @Output() valueChange = new EventEmitter<boolean>();

  @HostListener('click')
  toggle() {
    this.selected = !this.selected;
    this.valueChange.emit(this.selected);
  }

  getClassList() {
    return [`variant--${this.variant}`, `size--${this.size}`, this.selected ? 'selected' : ''].join(' ');
  }
}

// packages/vue/src/components/toggle/toggle.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Toggle } from 'reka-ui'
import { cva, type VariantProps } from 'class-variance-authority'

const toggleVariants = cva('q-toggle', {
  variants: {
    variant: {
      primary: 'variant--primary',
      outline: 'variant--outline',
      default: 'variant--default'
    },
    size: {
      sm: 'size--sm',
      md: 'size--md',
      lg: 'size--lg'
    }
  },
  defaultVariants: {
    variant: 'primary',
    size: 'md'
  }
})

export type ToggleVariants = VariantProps<typeof toggleVariants>

export interface ToggleProps {
  variant?: ToggleVariants['variant']
  size?: ToggleVariants['size']
  pressed?: boolean
  defaultPressed?: boolean
  disabled?: boolean
  asChild?: boolean
  value?: string
}

const props = withDefaults(defineProps<ToggleProps>(), {
  variant: 'primary',
  size: 'md',
  defaultPressed: false,
  disabled: false,
  asChild: false
})

const emit = defineEmits<{
  'update:pressed': [value: boolean]
}>()

const classes = computed(() => {
  return toggleVariants({
    variant: props.variant,
    size: props.size
  })
})

const handlePressedChange = (pressed: boolean) => {
  emit('update:pressed', pressed)
}
</script>

<template>
  <Toggle
    :pressed="pressed"
    :default-pressed="defaultPressed"
    :disabled="disabled"
    :as-child="asChild"
    :class="classes"
    @update:pressed="handlePressedChange"
    v-bind="$attrs"
  >
    <slot />
  </Toggle>
</template>

<style scoped>
button,
[role='button'] {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--spacing-2);
  border: 0;
  margin: 0;
  border-radius: var(--border-radius-md);
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-medium);
  color: var(--color-background-fg);
  transition: colors 0.3s;
  outline: none;
}

button:hover:not(:disabled),
[role='button']:hover:not(:disabled) {
  background-color: var(--color-muted);
  color: var(--color-muted-fg);
}

button:focus-visible,
[role='button']:focus-visible {
  outline: none;
  box-shadow: 0 0 0 1px var(--color-ring);
}

button:disabled,
[role='button'][aria-disabled='true'],
button[data-disabled],
[role='button'][data-disabled] {
  pointer-events: none;
  opacity: 0.5;
}

/* Variant modifiers */
.variant--default {
  background-color: var(--color-card);
  color: var(--color-card-fg);
  box-shadow: var(--box-shadow-sm);
}

.variant--default[data-state='on'] {
  background-color: var(--color-primary);
  color: var(--color-primary-fg);
}

.variant--primary {
  background-color: transparent;
  border: var(--border-width-default) solid var(--color-muted);
}

.variant--primary:not([data-state='on']) {
  background-color: transparent;
  border: var(--border-width-default) solid var(--color-muted);
}

.variant--primary[data-state='on'] {
  background-color: var(--color-primary);
  color: var(--color-primary-fg);
}

.variant--outline {
  border: var(--border-width-default) solid var(--color-input);
  background-color: transparent;
  box-shadow: var(--box-shadow-sm);
}

.variant--outline:not([data-state='on']) {
  border: var(--border-width-default) solid var(--color-input);
  background-color: transparent;
  box-shadow: var(--box-shadow-sm);
}

.variant--outline[data-state='on'] {
  border: var(--border-width-default) solid var(--color-primary);
}

/* Size modifiers */
.size--sm {
  height: var(--spacing-8);
  padding-left: var(--spacing-2);
  padding-right: var(--spacing-2);
}

.size--md {
  height: var(--spacing-9);
  padding-left: var(--spacing-3);
  padding-right: var(--spacing-3);
}

.size--lg {
  height: var(--spacing-10);
  padding-left: var(--spacing-3);
  padding-right: var(--spacing-3);
}
</style>
