// packages/angular/src/components/combobox/combobox-content.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CdkListbox, CdkListboxModule } from '@angular/cdk/listbox';

@Component({
  selector: '[qui-combobox-content]',
  standalone: true,
  imports: [CommonModule, CdkListboxModule],
  host: {
    role: 'listbox',
    id: 'combobox-content',
    '[attr.tabindex]': '-1',
    'data-testid': 'qui-combobox-content',
  },
  hostDirectives: [CdkListbox],
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        width: 100%;
        border-radius: var(--border-radius-md);
        border: 1px solid var(--color-border);
        background-color: var(--color-input);
        color: var(--color-input-fg);
        font-size: var(--font-size-sm);
        line-height: var(--line-height-sm);
        max-height: 15rem;
        overflow: auto;
        list-style: none;
        margin: 0;
        padding: 0;
      }
    `,
  ],
})
export class ComboboxContentComponent {}

// packages/vue/src/components/combobox/combobox-content.vue
<script setup lang="ts">
import { PopoverContent } from 'reka-ui'

export interface ComboboxContentProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<ComboboxContentProps>(), {
  asChild: false,
  as: 'div'
})
</script>

<template>
  <PopoverContent
    :as-child="asChild"
    :as="as"
    :class="['q-combobox-content']"
    role="listbox"
    id="combobox-content"
    tabindex="-1"
    v-bind="$attrs"
  >
    <slot />
  </PopoverContent>
</template>

<style scoped>
.q-combobox-content {
  width: 100%;
  border-radius: var(--border-radius-md);
  border: var(--border-width-default) solid var(--color-border);
  background-color: var(--color-input);
  color: var(--color-input-fg);
  font-size: var(--font-size-sm);
  line-height: var(--line-height-sm);
  max-height: var(--spacing-60);
  overflow: auto;
  list-style: none;
  margin: 0;
  padding: 0;
  z-index: 50;
}
</style>
