// packages/vue/src/components/timeline/timeline-separator.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface TimelineSeparatorProps {
  asChild?: boolean;
  as?: "div";
}

const props = withDefaults(defineProps<TimelineSeparatorProps>(), {
  asChild: false,
  as: "div",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-timeline-separator']"
    data-testid="qui-timeline-separator"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  width: var(--border-width-default);
  height: 100%;
  background-color: var(--color-border);
  margin: 0 auto;
}
</style>

// packages/angular/src/components/timeline/timeline-separator.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-timeline-separator]',
  standalone: true,
  host: {
    'data-testid': 'qui-timeline-separator',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        width: 1px;
        height: 100%;
        background-color: var(--color-border);
        margin: 0 auto;
      }
    `,
  ],
})
export class TimelineSeparatorComponent {}
