// packages/vue/src/components/header/header-backdrop-image.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeaderBackdropImageProps {
  src?: string;
  alt?: string;
  as?: "img";
  asChild?: boolean;
}

const props = withDefaults(defineProps<HeaderBackdropImageProps>(), {
  as: "img",
  asChild: false,
  alt: "",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-header-backdrop-image']"
    :src="src"
    :alt="alt"
    data-testid="qui-header-backdrop-image"
    v-bind="$attrs"
  />
</template>

<style scoped>
img {
  position: absolute;
  z-index: -10;
  height: 100%;
  width: 100%;
  object-fit: cover;
  filter: brightness(0.25);
}
</style>

// packages/angular/src/components/header/header-backdrop-image.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'img[qui-header-backdrop-image]',
  standalone: true,
  host: {
    'data-testid': 'qui-header-backdrop-image',
  },
  template: '',
  styles: [
    `
      :host {
        position: absolute;
        z-index: -10;
        height: 100%;
        width: 100%;
        object-fit: cover;
        filter: brightness(0.25);
      }
    `,
  ],
})
export class HeaderBackdropImageComponent {}
