// packages/vue/src/components/header/header-actions.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeaderActionsProps {
  as?: "div";
  asChild?: boolean;
}

const props = withDefaults(defineProps<HeaderActionsProps>(), {
  as: "div",
  asChild: false,
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-header-actions']"
    data-testid="qui-header-actions"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  margin-right: auto;
  display: flex;
  gap: var(--spacing-8);
}
</style>

// packages/angular/src/components/header/header-actions.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-header-actions]',
  standalone: true,
  host: {
    'data-testid': 'qui-header-actions',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        margin-right: auto;
        display: flex;
        gap: var(--spacing-8);
      }
    `,
  ],
})
export class HeaderActionsComponent {}
