// packages/vue/src/components/cookie-consent/cookie-consent.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import ButtonComponent from '../button/button.vue'
import { X } from 'lucide-vue-next'

const CONSENT_KEY = 'cookieConsent'

const showBanner = ref(false)

const getConsent = (): string | null => {
  if (typeof window === 'undefined') return null
  return localStorage.getItem(CONSENT_KEY)
}

const setConsent = (consent: string): void => {
  if (typeof window === 'undefined') return
  localStorage.setItem(CONSENT_KEY, consent)
}

const clearConsent = (): void => {
  if (typeof window === 'undefined') return
  localStorage.removeItem(CONSENT_KEY)
}

onMounted(() => {
  const consent = getConsent()
  if (consent === null) {
    showBanner.value = true
  }
})

const handleAccept = () => {
  setConsent('accepted')
  showBanner.value = false
}

const handleReject = () => {
  setConsent('rejected')
  showBanner.value = false
}
</script>

<template>
  <div
    v-if="showBanner"
    class="q-cookie-consent"
    data-testid="qui-cookie-consent"
  >
    <div
      class="q-cookie-consent-header"
      data-testid="qui-cookie-consent-header"
    >
      <div class="q-cookie-consent-text">
        <h3 class="q-cookie-consent-heading">Cookie Consent</h3>
      </div>
      <ButtonComponent
        variant="ghost"
        size="icon"
        @click="handleReject"
        class="q-cookie-consent-close"
        data-testid="qui-cookie-consent-close"
      >
        <span aria-hidden="true">
          <X :size="16" />
        </span>
        <span class="q-sr-only">Close</span>
      </ButtonComponent>
    </div>
    <div class="q-cookie-consent-content">
      <p class="q-cookie-consent-text-body">
        We use cookies to enhance your browsing experience and analyze our
        traffic. By clicking "Accept", you consent to our use of cookies.
      </p>
    </div>
    <div class="q-cookie-consent-actions">
      <ButtonComponent
        variant="outline"
        @click="handleReject"
        class="q-cookie-consent-button-reject"
        data-testid="qui-cookie-consent-reject"
      >
        Reject
      </ButtonComponent>
      <ButtonComponent
        variant="primary"
        @click="handleAccept"
        class="q-cookie-consent-button-accept"
        data-testid="qui-cookie-consent-accept"
      >
        Accept
      </ButtonComponent>
    </div>
  </div>
</template>

<style scoped>
.q-cookie-consent {
  position: fixed;
  bottom: var(--spacing-4);
  left: var(--spacing-4);
  right: var(--spacing-4);
  max-width: var(--columns-xl);
  margin: 0 auto;
  z-index: var(--z-index-50);
  background-color: var(--color-card);
  box-shadow: var(--box-shadow-lg);
  border-radius: var(--border-radius-lg);
}

.q-cookie-consent-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--spacing-3) var(--spacing-4);
}

.q-cookie-consent-content {
  padding: 0 var(--spacing-4);
  display: flex;
  justify-content: space-between;
  align-items: start;
}

.q-cookie-consent-heading {
  margin: 0;
  font-size: var(--font-size-lg);
  font-weight: var(--font-weight-semibold);
  line-height: var(--line-height-tight);
  color: var(--color-background-fg);
}

.q-cookie-consent-text-body {
  margin: 0;
  font-size: var(--font-size-base);
  line-height: var(--line-height-relaxed);
  color: var(--color-background-fg);
}

.q-cookie-consent-close {
  background: none;
  border: none;
  cursor: pointer;
  font-size: var(--font-size-lg);
  color: var(--color-muted-fg);
}

.q-cookie-consent-actions {
  display: flex;
  justify-content: flex-end;
  padding: var(--spacing-4);
  gap: var(--spacing-4);
}

.q-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
</style>

// packages/angular/src/components/cookie-consent/cookie-consent.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { CookieConsentService } from './cookie-consent.service';
import { VisuallyHiddenComponent } from '../visually-hidden/visually-hidden.component';
import { ButtonComponent } from '../button/button.component';
import { CommonModule } from '@angular/common';
import { TextComponent } from '../text/text.component';
import { HeadingComponent } from '../heading/heading.component';
import { IconCross2Component } from '../../icons';

@Component({
  selector: 'qui-cookie-consent',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    VisuallyHiddenComponent,
    TextComponent,
    HeadingComponent,
    IconCross2Component,
  ],
  template: `
    <div
      *ngIf="showBanner"
      class="cookie-consent-banner"
      data-testid="qui-cookie-consent"
    >
      <div
        class="cookie-consent-header"
        data-testid="qui-cookie-consent-header"
      >
        <div class="cookie-consent-text">
          <h3 qui-heading variant="h3">Cookie Consent</h3>
        </div>
        <button
          qui-button
          variant="ghost"
          size="icon"
          (click)="handleReject()"
          class="cookie-consent-close"
          data-testid="qui-cookie-consent-close"
        >
          <span aria-hidden="true">
            <i qui-icon name="cross2" size="sm"></i>
          </span>
          <span qui-sr-only>Close</span>
        </button>
      </div>
      <div class="cookie-consent-content">
        <p qui-text variant="body">
          We use cookies to enhance your browsing experience and analyze our
          traffic. By clicking "Accept", you consent to our use of cookies.
        </p>
      </div>
      <div class="cookie-consent-actions">
        <button
          qui-button
          variant="outline"
          (click)="handleReject()"
          class="cookie-consent-button-reject"
          data-testid="qui-cookie-consent-reject"
        >
          Reject
        </button>
        <button
          qui-button
          variant="primary"
          (click)="handleAccept()"
          class="cookie-consent-button-accept"
          data-testid="qui-cookie-consent-accept"
        >
          Accept
        </button>
      </div>
    </div>
  `,
  styles: [
    `
      .cookie-consent-banner {
        position: fixed;
        bottom: var(--spacing-4);
        left: var(--spacing-4);
        right: var(--spacing-4);
        max-width: var(--columns-xl);
        margin: 0 auto;
        z-index: var(--z-index-50);
        background-color: var(--color-card);
        box-shadow: var(--box-shadow-lg);
        border-radius: var(--border-radius-lg);
      }

      .cookie-consent-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: var(--spacing-3) var(--spacing-4);
      }

      .cookie-consent-content {
        padding: 0 var(--spacing-4);
        display: flex;
        justify-content: space-between;
        align-items: start;
      }

      .cookie-consent-close {
        background: none;
        border: none;
        cursor: pointer;
        font-size: var(--font-size-lg);
        color: var(--color-muted-fg);
      }

      .cookie-consent-actions {
        display: flex;
        justify-content: flex-end;
        padding: var(--spacing-4);
        gap: var(--spacing-4);
      }

      .cookie-consent-button-outline {
        border: var(--border-width-default) solid var(--color-border);
        background-color: transparent;
        color: var(--color-background-fg);
        padding: var(--spacing-2) var(--spacing-4);
        border-radius: var(--border-radius-md);
        cursor: pointer;
      }

      .cookie-consent-button {
        background-color: var(--color-primary);
        color: var(--color-primary-fg);
        padding: var(--spacing-2) var(--spacing-4);
        border-radius: var(--border-radius-md);
        cursor: pointer;
        border: none;
      }
    `,
  ],
})
export class CookieConsentComponent implements OnInit {
  showBanner = false;

  constructor(
    @Inject(CookieConsentService)
    private cookieConsentService: CookieConsentService
  ) {}

  ngOnInit() {
    const consent = this.cookieConsentService.getConsent();
    if (consent === null) {
      this.showBanner = true;
    }
  }

  handleAccept() {
    this.cookieConsentService.setConsent('accepted');
    this.showBanner = false;
  }

  handleReject() {
    this.cookieConsentService.setConsent('rejected');
    this.showBanner = false;
  }
}
