// packages/angular/src/components/card/card-description.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-card-description]',
  template: `<ng-content></ng-content>`,
  host: {
    'data-testid': 'qui-card-description',
  },
  styles: [
    `
      :host {
        font-size: var(--font-size-sm);
        color: var(--color-muted-fg);
        margin: 0;
      }
    `,
  ],
  standalone: true,
})
export class CardDescriptionComponent {}

// packages/vue/src/components/card/card-description.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface CardDescriptionProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<CardDescriptionProps>(), {
  asChild: false,
  as: 'p'
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-card-description']"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
p {
  font-size: var(--font-size-sm);
  color: var(--color-muted-fg);
  margin: 0;
}
</style>
