// packages/vue/src/components/card/card-footer.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface CardFooterProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<CardFooterProps>(), {
  asChild: false,
  as: 'div'
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-card-footer']"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
  align-items: center;
  padding: var(--spacing-6);
  padding-top: var(--spacing-0);
}
</style>

// packages/angular/src/components/card/card-footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[pui-card-footer]',
  host: {
    'data-testid': 'pui-card-footer',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: flex;
        justify-content: center;
        padding: var(--spacing-5);
        padding-top: 0;
      }
    `,
  ],
  standalone: true,
})
export class CardFooterComponent {}
