// packages/angular/src/components/tab-navigation/tab-navigation-item.component.ts
// src/components/tab-navigation/tab-navigation-link.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'li[qui-tab-navigation-item]',
  template: ` <ng-content></ng-content> `,
  host: {
    'data-testid': 'tab-navigation__item',
  },
  styles: [
    `
      :host {
        list-style: none;
        margin: 0;
        padding: 0;
      }
    `,
  ],
  standalone: true,
})
export class TabNavigationItemComponent {}

// packages/vue/src/components/tab-navigation/tab-navigation-item.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface TabNavigationItemProps {
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TabNavigationItemProps>(), {
  asChild: false,
  as: "li",
});

const classes = computed(() => ["q-tab-navigation-item"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    data-testid="qui-tab-navigation-item"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-tab-navigation-item {
  list-style: none;
  margin: 0;
  padding: 0;
}
</style>
