// packages/angular/src/components/tab-navigation/tab-navigation-menugroup.component.ts
import { CdkMenuGroup } from '@angular/cdk/menu';
import { Component } from '@angular/core';

@Component({
  selector: '[qui-tab-navigation-menugroup]',
  host: {
    'data-testid': 'qui-tab-navigation-menugroup',
  },
  template: '<ng-content></ng-content>',
  hostDirectives: [CdkMenuGroup],
  styles: [
    `
      :host {
        padding: 0;
        margin: 0;
        overflow: hidden auto;
      }
    `,
  ],
  standalone: true,
})
export class TabNavigationMenugroupComponent {}

// packages/vue/src/components/tab-navigation/tab-navigation-menugroup.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface TabNavigationMenugroupProps {
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TabNavigationMenugroupProps>(), {
  asChild: false,
  as: "ol",
});

const classes = computed(() => ["q-tab-navigation-menugroup"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    data-testid="qui-tab-navigation-menugroup"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
ol {
  padding: 0;
  margin: 0;
  overflow: hidden auto;
}
</style>
