// packages/vue/src/components/toggle-group/toggle-group.vue
<script setup lang="ts">
import { computed, provide, ref, watch } from "vue";
import { ToggleGroupRoot } from "reka-ui";
import { cva, type VariantProps } from "class-variance-authority";

const toggleGroupVariants = cva("q-toggle-group", {
  variants: {
    variant: {
      primary: "variant--primary",
      outline: "variant--outline",
      default: "variant--default",
    },
    size: {
      sm: "size--sm",
      md: "size--md",
      lg: "size--lg",
    },
  },
  defaultVariants: {
    variant: "primary",
    size: "md",
  },
});

export type ToggleGroupVariants = VariantProps<typeof toggleGroupVariants>;

export interface ToggleGroupProps {
  type?: "single" | "multiple";
  value?: string | string[];
  defaultValue?: string | string[];
  variant?: ToggleGroupVariants["variant"];
  size?: ToggleGroupVariants["size"];
  disabled?: boolean;
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<ToggleGroupProps>(), {
  type: "single",
  variant: "primary",
  size: "md",
  disabled: false,
  asChild: false,
  as: "div",
});

const emit = defineEmits<{
  "update:value": [value: string | string[]];
}>();

// Internal state management
const isControlled = props.value !== undefined;
const internalValue = ref<string | string[]>(
  props.defaultValue ?? (props.type === "single" ? "" : [])
);
const selectedValue = computed(() =>
  isControlled ? props.value : internalValue.value
);

const handleValueChange = (value: string | string[]) => {
  if (!isControlled) {
    internalValue.value = value;
  }
  emit("update:value", value);
};

// Watch for external changes
watch(
  () => props.value,
  (newValue) => {
    if (isControlled && newValue !== undefined) {
      internalValue.value = newValue;
    }
  }
);

const classes = computed(() => {
  return toggleGroupVariants({
    variant: props.variant,
    size: props.size,
  });
});

// Provide context to child components
provide("toggleGroupContext", {
  variant: computed(() => props.variant),
  size: computed(() => props.size),
});
</script>

<template>
  <ToggleGroupRoot
    :type="type"
    :model-value="selectedValue"
    :default-value="defaultValue"
    :disabled="disabled"
    :as-child="asChild"
    :as="as"
    :class="classes"
    @update:model-value="handleValueChange"
    v-bind="$attrs"
  >
    <slot />
  </ToggleGroupRoot>
</template>

<style scoped>
.q-toggle-group {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--spacing-1);
}
</style>

// packages/react/src/components/toggle-group/toggle-group.tsx
import * as ToggleGroupPrimitive from "@radix-ui/react-toggle-group";
import { VariantProps } from "class-variance-authority";
import * as React from "react";
import styled from "styled-components";

import { toggleVariants, toggleStyles } from "@/components/toggle/toggle";

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants>
>({
  size: "md",
  variant: "primary",
});

const StyledToggleGroupRoot = styled(ToggleGroupPrimitive.Root)`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--spacing-1);
`;

const ToggleGroup = React.forwardRef<
  React.ElementRef<typeof ToggleGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Root> &
    VariantProps<typeof toggleVariants>
>(({ className, variant, size, children, ...props }, ref) => (
  <StyledToggleGroupRoot ref={ref} className={className} {...props}>
    <ToggleGroupContext.Provider value={{ variant, size }}>
      {children}
    </ToggleGroupContext.Provider>
  </StyledToggleGroupRoot>
));

ToggleGroup.displayName = ToggleGroupPrimitive.Root.displayName;

const StyledToggleGroupItem = styled(ToggleGroupPrimitive.Item)`
  ${toggleStyles}
`;

const ToggleGroupItem = React.forwardRef<
  React.ElementRef<typeof ToggleGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Item> &
    VariantProps<typeof toggleVariants>
>(({ className, children, variant, size, ...props }, ref) => {
  const context = React.useContext(ToggleGroupContext);

  const classes = toggleVariants({
    variant: context.variant || variant,
    size: context.size || size,
  });

  const combinedClassName = className
    ? `${classes} ${className}`.trim()
    : classes;

  return (
    <StyledToggleGroupItem ref={ref} className={combinedClassName} {...props}>
      {children}
    </StyledToggleGroupItem>
  );
});

ToggleGroupItem.displayName = ToggleGroupPrimitive.Item.displayName;

export { ToggleGroup, ToggleGroupItem };
