// packages/angular/src/components/reel/reel-item.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[pui-reel-item]',
  template: `<ng-content></ng-content>`,
  standalone: true,
  host: {
    'data-testid': 'pui-reel-item',
  },
  styles: [
    `
      :host {
        flex: 0 0 auto;
        scroll-snap-align: start;
      }
    `,
  ],
})
export class ReelItemComponent {}

// packages/vue/src/components/reel/reel-item.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface ReelItemProps {
  asChild?: boolean
}

const props = withDefaults(defineProps<ReelItemProps>(), {
  asChild: false
})
</script>

<template>
  <Primitive
    :as="'div'"
    :as-child="asChild"
    :class="['q-reel-item']"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-reel-item {
  flex: 0 0 auto;
  scroll-snap-align: start;
}
</style>
