// packages/angular/src/components/breadcrumb/breadcrumb-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'span[qui-breadcrumb-page]',
  standalone: true,
  host: {
    'data-testid': 'qui-breadcrumb-page',
    '[attr.aria-current]': 'page',
  },
  styles: [
    `
      :host {
        color: var(--color-background-fg);
        padding-bottom: var(--spacing-1);
      }
    `,
  ],
  template: `<ng-content></ng-content>`,
})
export class BreadcrumbPageComponent {}

// packages/vue/src/components/breadcrumb/breadcrumb-page.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface BreadcrumbPageProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<BreadcrumbPageProps>(), {
  asChild: false,
});
</script>

<template>
  <Primitive
    as="span"
    :as-child="asChild"
    aria-current="page"
    data-testid="qui-breadcrumb-page"
    class="q-breadcrumb-page"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
span {
  color: var(--color-background-fg);
  padding-bottom: var(--spacing-1);
}
</style>
