// packages/vue/src/components/hero/hero.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeroProps {
  asChild?: boolean;
  as?: "div";
}

const props = withDefaults(defineProps<HeroProps>(), {
  asChild: false,
  as: "div",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-hero"
    data-testid="qui-hero"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: grid;
  grid-template-columns: repeat(1, minmax(0, 1fr));
  align-items: center;
  gap: var(--spacing-14);
}

@media (min-width: 1024px) {
  div {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}
</style>

// packages/angular/src/components/hero/hero.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-hero]',
  standalone: true,
  host: {
    'data-testid': 'qui-hero',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: grid;
        grid-template-columns: 1fr;
        align-items: center;
        gap: var(--spacing-14);
      }

      @media (width >= 1024px) {
        :host {
          grid-template-columns: repeat(2, 1fr);
        }
      }
    `,
  ],
})
export class HeroComponent {}
