// packages/vue/src/components/hero/hero-body.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeroBodyProps {
  asChild?: boolean;
  as?: "p";
}

const props = withDefaults(defineProps<HeroBodyProps>(), {
  asChild: false,
  as: "p",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-hero-body"
    data-testid="qui-hero-body"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
p {
  font-size: var(--font-size-lg);
  color: hsl(from var(--color-background-fg) h s l / 66%);
  margin: 0;
}
</style>

// packages/angular/src/components/hero/hero-body.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-hero-body]',
  standalone: true,
  host: {
    'data-testid': 'qui-hero-body',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        font-size: var(--font-size-lg);
        color: hsl(from var(--color-background-fg) h s l / 66%);
        margin: 0;
      }
    `,
  ],
})
export class HeroBodyComponent {}
