// packages/vue/src/components/hero/hero-title.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeroTitleProps {
  asChild?: boolean;
  as?: "h1";
}

const props = withDefaults(defineProps<HeroTitleProps>(), {
  asChild: false,
  as: "h1",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-hero-title"
    data-testid="qui-hero-title"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
h1 {
  font-size: var(--font-size-4xl);
  font-weight: var(--font-weight-bold);
  line-height: var(--line-height-tight);
  letter-spacing: var(--tracking-wide);
  color: var(--color-background-fg);
  margin: 0;
}

@media (min-width: 1280px) {
  h1 {
    font-size: var(--font-size-5xl);
  }
}
</style>

// packages/angular/src/components/hero/hero-title.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'h1[qui-hero-title]',
  standalone: true,
  host: {
    'data-testid': 'qui-hero-title',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        font-size: var(--font-size-4xl);
        font-weight: var(--font-weight-bold);
        line-height: var(--line-height-tight);
        color: var(--color-background-fg);
        letter-spacing: var(--tracking-wide);
        margin: 0;
      }

      @media (width >= 1280px) {
        :host {
          font-size: var(--font-size-5xl);
        }
      }
    `,
  ],
})
export class HeroTitleComponent {}
