// packages/vue/src/components/toggle-group/toggle-group.vue
<script setup lang="ts">
import { computed, provide, ref, watch } from "vue";
import { ToggleGroupRoot } from "reka-ui";
import { cva, type VariantProps } from "class-variance-authority";

const toggleGroupVariants = cva("q-toggle-group", {
  variants: {
    variant: {
      primary: "variant--primary",
      outline: "variant--outline",
      default: "variant--default",
    },
    size: {
      sm: "size--sm",
      md: "size--md",
      lg: "size--lg",
    },
  },
  defaultVariants: {
    variant: "primary",
    size: "md",
  },
});

export type ToggleGroupVariants = VariantProps<typeof toggleGroupVariants>;

export interface ToggleGroupProps {
  type?: "single" | "multiple";
  value?: string | string[];
  defaultValue?: string | string[];
  variant?: ToggleGroupVariants["variant"];
  size?: ToggleGroupVariants["size"];
  disabled?: boolean;
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<ToggleGroupProps>(), {
  type: "single",
  variant: "primary",
  size: "md",
  disabled: false,
  asChild: false,
  as: "div",
});

const emit = defineEmits<{
  "update:value": [value: string | string[]];
}>();

// Internal state management
const isControlled = props.value !== undefined;
const internalValue = ref<string | string[]>(
  props.defaultValue ?? (props.type === "single" ? "" : [])
);
const selectedValue = computed(() =>
  isControlled ? props.value : internalValue.value
);

const handleValueChange = (value: string | string[]) => {
  if (!isControlled) {
    internalValue.value = value;
  }
  emit("update:value", value);
};

// Watch for external changes
watch(
  () => props.value,
  (newValue) => {
    if (isControlled && newValue !== undefined) {
      internalValue.value = newValue;
    }
  }
);

const classes = computed(() => {
  return toggleGroupVariants({
    variant: props.variant,
    size: props.size,
  });
});

// Provide context to child components
provide("toggleGroupContext", {
  variant: computed(() => props.variant),
  size: computed(() => props.size),
});
</script>

<template>
  <ToggleGroupRoot
    :type="type"
    :value="selectedValue"
    :default-value="defaultValue"
    :disabled="disabled"
    :as-child="asChild"
    :as="as"
    :class="classes"
    @update:value="handleValueChange"
    v-bind="$attrs"
  >
    <slot />
  </ToggleGroupRoot>
</template>

<style scoped>
.q-toggle-group {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  isolation: isolate;
  border-radius: var(--border-radius-md);
  box-shadow: var(--box-shadow-default);
}

.q-toggle-group :deep(a),
.q-toggle-group :deep(button) {
  position: relative;
  border-radius: 0;
  border-left: 1px solid var(--color-border);
  margin: 0;
}

.q-toggle-group :deep(a:first-child),
.q-toggle-group :deep(button:first-child) {
  border-top-left-radius: var(--border-radius-md);
  border-bottom-left-radius: var(--border-radius-md);
  border-left: none;
}

.q-toggle-group :deep(a:last-child),
.q-toggle-group :deep(button:last-child) {
  border-top-right-radius: var(--border-radius-md);
  border-bottom-right-radius: var(--border-radius-md);
  border-left: none;
}
</style>

// packages/angular/src/components/toggle-group/toggle-group.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  ContentChildren,
  QueryList,
  AfterContentInit,
  Input,
} from '@angular/core';
import { ToggleComponent } from '../toggle/toggle.component';
import { BehaviorSubject } from 'rxjs';

export type ToggleGroupVariants = {
  variant: 'default' | 'outline';
  size: 'sm' | 'md' | 'lg';
};

@Component({
  selector: 'div[qui-toggle-group]',
  standalone: true,
  imports: [CommonModule, ToggleComponent],
  host: {
    'data-testid': 'toggle-group',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      /* stylelint-disable selector-pseudo-element-no-unknown */
      :host {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        isolation: isolate;
        border-radius: var(--border-radius-md);
        box-shadow: var(--box-shadow-default);
      }

      :host ::ng-deep a,
      :host ::ng-deep button {
        position: relative;
        border-radius: 0;
        border-left: 1px solid var(--color-border);
        margin: 0;
      }

      :host ::ng-deep a:first-child,
      :host ::ng-deep button:first-child {
        border-top-left-radius: var(--border-radius-md);
        border-bottom-left-radius: var(--border-radius-md);
        border-left: none;
      }

      :host ::ng-deep a:last-child,
      :host ::ng-deep button:last-child {
        border-top-right-radius: var(--border-radius-md);
        border-bottom-right-radius: var(--border-radius-md);
        border-left: none;
      }
    `,
  ],
})
export class ToggleGroupComponent implements AfterContentInit {
  @Input() strategy: 'single' | 'multiple' = 'single';
  @Input() variant: ToggleGroupVariants['variant'] = 'default';
  @Input() size: ToggleGroupVariants['size'] = 'md';
  @ContentChildren(ToggleComponent, { descendants: true })
  toggles!: QueryList<ToggleComponent>;
  selectedOptions$ = new BehaviorSubject<string[]>([]);

  ngAfterContentInit() {
    this.selectedOptions$.subscribe((value) => {
      if (value.length === 0) {
        this.toggles.forEach((toggle) => {
          toggle.selected = false;
        });
        return;
      }

      this.toggles.forEach((toggle) => {
        toggle.selected = value.includes(toggle.value);
      });
    });

    this.toggles.forEach((toggle) => {
      toggle.variant = this.variant;
      toggle.size = this.size;
      toggle.valueChange.subscribe((selected) => {
        if (this.strategy === 'single') {
          if (selected) {
            this.selectedOptions$.next([toggle.value]);
          } else {
            this.selectedOptions$.next([]);
          }
        } else if (this.strategy === 'multiple') {
          const current = this.selectedOptions$.getValue();
          if (!selected) {
            this.selectedOptions$.next(
              current.filter((v) => v !== toggle.value)
            );
            return;
          }
          this.selectedOptions$.next([...current, toggle.value]);
        }
      });
    });
  }
}
