// packages/vue/src/components/footer/footer-banner-list.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface FooterBannerListProps {
  as?: "nav" | "ul";
  asChild?: boolean;
}

const props = withDefaults(defineProps<FooterBannerListProps>(), {
  as: "nav",
  asChild: false,
});

const footerBannerListClasses = computed(() => ["q-footer-banner-list"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="footerBannerListClasses"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
nav,
ul {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-4);
  margin: 0;
  padding: 0;
}

@media (width >= 768px) {
  nav,
  ul {
    flex-direction: row;
  }
}
</style>

// packages/angular/src/components/footer/footer-banner-list.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: '[pui-footer-banner-list]',
  standalone: true,
  host: {
    'data-testid': 'pui-footer-banner-list',
  },
  imports: [CommonModule],
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        gap: var(--spacing-4);
        margin: 0;
        padding: 0;
      }

      @media (width >= 768px) {
        :host {
          flex-direction: row;
        }
      }
    `,
  ],
  template: `<ng-content></ng-content>`,
})
export class FooterBannerListComponent {}
