// packages/vue/src/components/footer/footer-section.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface FooterSectionProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<FooterSectionProps>(), {
  asChild: false,
});

const footerSectionClasses = computed(() => ["q-footer-section"]);
</script>

<template>
  <Primitive
    as="div"
    :as-child="asChild"
    :class="footerSectionClasses"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
  max-width: var(--breakpoint-xs);
  flex-direction: column;
  gap: var(--spacing-4);
}

@media (width >= 640px) {
  div {
    max-width: var(--breakpoint-lg);
  }
}
</style>

// packages/angular/src/components/footer/footer-section.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'div[pui-footer-section]',
  standalone: true,
  host: {
    'data-testid': 'pui-footer-section',
  },
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: flex;
        max-width: var(--breakpoint-xs);
        flex-direction: column;
        gap: var(--spacing-4);
      }

      @media (width >= 640px) {
        :host {
          max-width: var(--breakpoint-lg);
        }
      }
    `,
  ],
})
export class FooterSectionComponent {}
