// packages/vue/src/components/footer/footer-heading.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface FooterHeadingProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<FooterHeadingProps>(), {
  asChild: false,
});

const footerHeadingClasses = computed(() => ["q-footer-heading"]);
</script>

<template>
  <Primitive
    as="h3"
    :as-child="asChild"
    :class="footerHeadingClasses"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
h3 {
  display: block;
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-semibold);
  line-height: var(--line-height-6);
  color: var(--color-background-fg);
  margin: 0;
  padding: 0;
}
</style>

// packages/angular/src/components/footer/footer-heading.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'h3[qui-footer-heading]',
  standalone: true,
  host: {
    'data-testid': 'qui-footer-heading',
  },
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: block;
        font-size: var(--font-size-sm);
        font-weight: var(--font-weight-semibold);
        line-height: var(--line-height-6);
        color: var(--color-background-fg);
        margin: 0;
        padding: 0;
      }
    `,
  ],
})
export class FooterHeadingComponent {}
