// packages/vue/src/components/footer/footer-columns.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface FooterColumnsProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<FooterColumnsProps>(), {
  asChild: false,
});

const footerColumnsClasses = computed(() => ["q-footer-columns"]);
</script>

<template>
  <Primitive
    as="div"
    :as-child="asChild"
    :class="footerColumnsClasses"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: block;
}

@media (width >= 640px) {
  div {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: var(--spacing-10);
  }
}

@media (width >= 1280px) {
  div {
    gap: var(--spacing-20);
  }
}
</style>

// packages/angular/src/components/footer/footer-columns.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'div[pui-footer-columns]',
  standalone: true,
  host: {
    'data-testid': 'pui-footer-columns',
  },
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: block;
      }

      @media (width >= 640px) {
        :host {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: var(--spacing-10);
        }
      }

      @media (width >= 1280px) {
        :host {
          gap: var(--spacing-20);
        }
      }
    `,
  ],
})
export class FooterColumnsComponent {}
