// packages/vue/src/components/tabs/tabs-trigger.vue
<script setup lang="ts">
import { TabsTrigger as RekaTabsTrigger } from "reka-ui";

export interface TabsTriggerProps {
  value: string;
  disabled?: boolean;
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TabsTriggerProps>(), {
  disabled: false,
  asChild: false,
  as: "button",
});
</script>

<template>
  <RekaTabsTrigger
    :value="value"
    :disabled="disabled"
    :as-child="asChild"
    :as="as"
    :class="['q-tabs-trigger']"
    data-testid="qui-tabs-trigger"
    v-bind="$attrs"
  >
    <slot />
  </RekaTabsTrigger>
</template>

<style scoped>
button,
[role="tab"] {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  white-space: nowrap;
  border-radius: var(--border-radius-sm);
  padding-left: var(--spacing-3);
  padding-right: var(--spacing-3);
  padding-top: var(--spacing-1-5);
  padding-bottom: var(--spacing-1-5);
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-medium);
  box-shadow: 0 0 0 0 var(--color-background);
  color: var(--color-muted-fg);
  transition: all 0.3s;
  width: 100%;
  outline: none;
}

button:focus-visible,
[role="tab"]:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--color-ring), 0 0 0 4px var(--color-background);
}

button:disabled,
[role="tab"][aria-disabled="true"] {
  pointer-events: none;
  opacity: 0.5;
}

button[data-state="active"],
[role="tab"][data-state="active"] {
  background-color: hsl(from var(--color-background-fg) h s l / 10%);
  color: hsl(from var(--color-background-fg) h s l / 90%);
  box-shadow: var(--box-shadow-sm);
}
</style>

// packages/angular/src/components/tabs/tabs-trigger.component.ts
import { Component, ElementRef, Input, TemplateRef } from '@angular/core';

type TabsTriggerVariants = {
  variant: 'active' | 'default';
};

@Component({
  selector: '[qui-tabs-trigger]',
  template: `<ng-content></ng-content>`,
  host: {
    '[class]': 'getClassList()',
    'data-testid': 'qui-tabs-trigger',
    '[attr.aria-expanded]': 'variant === "active"',
  },
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        white-space: nowrap;
        border: 0 none;
        border-radius: var(--border-radius-md);
        padding: var(--spacing-1-5) var(--spacing-3);
        background-color: hsl(from var(--color-background) h s l / 66%);
        color: hsl(from var(--color-background-fg) h s l / 80%);
        font-size: var(--font-size-sm);
        font-weight: var(--font-weight-medium);
        transition: all 0.3s;
        outline: none;

        &:disabled {
          pointer-events: none;
          opacity: 0.5;
          color: var(--color-muted-fg);
        }
      }

      :host(.variant--active) {
        background-color: var(--color-background);
        color: var(--color-primary);
        border-bottom: 2px solid var(--color-primary);
        box-shadow: var(--box-shadow-sm);
      }
    `,
  ],
  standalone: true,
})
export class TabsTriggerComponent {
  @Input() variant: TabsTriggerVariants['variant'] = 'default';
  @Input() tabContentFor!: TemplateRef<unknown>;

  constructor(private elementRef: ElementRef) {}

  setClickListener(listener: () => void) {
    this.elementRef.nativeElement.addEventListener('click', listener);
  }

  getClassList() {
    return ['variant--' + this.variant].join(' ');
  }
}
