// packages/vue/src/components/tabs/tabs-content.vue
<script setup lang="ts">
import { TabsContent as RekaTabsContent } from "reka-ui";

export interface TabsContentProps {
  value: string;
  forceMount?: boolean;
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TabsContentProps>(), {
  forceMount: false,
  asChild: false,
  as: "div",
});
</script>

<template>
  <RekaTabsContent
    :value="value"
    :force-mount="forceMount"
    :as-child="asChild"
    :as="as"
    :class="['q-tabs-content']"
    data-testid="qui-tabs-content"
    v-bind="$attrs"
  >
    <slot />
  </RekaTabsContent>
</template>

<style scoped>
.q-tabs-content {
  margin-top: var(--spacing-2);
  box-shadow: 0 0 0 0 var(--color-background);
  outline: none;
}

.q-tabs-content:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--color-ring), 0 0 0 4px var(--color-background);
}
</style>

// packages/angular/src/components/tabs/tabs-content.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-tabs-content]',
  template: `<ng-content></ng-content>`,
  host: {
    'data-testid': 'qui-tabs-content',
  },
  styles: [
    `
      :host {
        margin-top: var(--spacing-2);
        outline: none;
      }
    `,
  ],
  standalone: true,
})
export class TabsContentComponent {}
