// packages/vue/src/components/loading-bar/loading-bar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

export interface LoadingBarProps {
  loading?: boolean
  asChild?: boolean
}

const props = withDefaults(defineProps<LoadingBarProps>(), {
  loading: false,
  asChild: false
})

const loadingBarClasses = computed(() => {
  return [
    'q-loading-bar',
    {
      loading: props.loading
    }
  ]
})
</script>

<template>
  <Primitive
    :as="asChild ? undefined : 'div'"
    :as-child="asChild"
    :class="loadingBarClasses"
    data-testid="qui-loading-bar"
    v-bind="$attrs"
  >
    <div v-if="loading" class="indicator"></div>
  </Primitive>
</template>

<style scoped>
div {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 4px;
  overflow: hidden;
  z-index: 1000;
}

.indicator {
  height: 100%;
  width: 100%;
  background-color: var(--color-primary);
  animation: indeterminate 1.5s infinite linear;
}

@keyframes indeterminate {
  0% {
    transform: translateX(-100%);
  }

  100% {
    transform: translateX(100%);
  }
}
</style>

// packages/angular/src/components/loading-bar/loading-bar.component.ts
import { AsyncPipe } from '@angular/common';
import {
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import { LoadingService } from './loading.service';

@Component({
  selector: 'qui-loading-bar',
  standalone: true,
  imports: [AsyncPipe],
  host: {
    'data-testid': 'qui-loading-bar',
  },
  template: `
    <div [class.indicator]="loadingService.loadingSubject | async"></div>
  `,
  styles: [
    `
      :host {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 4px;
        overflow: hidden;
        z-index: 1000;
      }

      :host .indicator {
        height: 100%;
        width: 100%;
        background-color: var(--color-primary);
        animation: indeterminate 1.5s infinite linear;
      }

      @keyframes indeterminate {
        0% {
          transform: translateX(-100%);
        }

        100% {
          transform: translateX(100%);
        }
      }
    `,
  ],
})
export class LoadingBarComponent implements OnInit, OnChanges {
  @Input() loading = false;

  constructor(protected loadingService: LoadingService) {}

  ngOnInit(): void {
    if (this.loading) {
      this.loadingService.start();
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['loading']) {
      if (this.loading) {
        this.loadingService.start();
      } else {
        this.loadingService.stop();
      }
    }
  }
}
