// packages/vue/src/components/avatar/avatar-fallback.vue
<script setup lang="ts">
import { AvatarFallback as RekaAvatarFallback } from 'reka-ui'

export interface AvatarFallbackProps {
  asChild?: boolean
}

const props = withDefaults(defineProps<AvatarFallbackProps>(), {
  asChild: false
})
</script>

<template>
  <RekaAvatarFallback
    :as-child="asChild"
    class="q-avatar-fallback"
    v-bind="$attrs"
  >
    <slot />
  </RekaAvatarFallback>
</template>

<style scoped>
.q-avatar-fallback {
  display: flex;
  height: 100%;
  width: 100%;
  align-items: center;
  justify-content: center;
  border-radius: var(--border-radius-full);
  background-color: var(--color-muted);
  color: var(--color-muted-fg);
}
</style>

// packages/angular/src/components/avatar/avatar-fallback.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-avatar-fallback], qui-avatar-fallback',
  standalone: true,
  host: {
    'data-testid': 'qui-avatar-fallback',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        display: flex;
        height: var(--size-full);
        width: var(--size-full);
        align-items: center;
        justify-content: center;
        border-radius: var(--border-radius-full);
        color: var(--color-muted-fg);
        background-color: var(--color-muted);
      }
    `,
  ],
})
export class AvatarFallbackComponent {}
