// packages/vue/src/components/tab-navigation/tab-navigation-rail.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface TabNavigationRailProps {
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TabNavigationRailProps>(), {
  asChild: false,
  as: "div",
});

const classes = computed(() => ["q-tab-navigation-rail"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    role="menubar"
    data-testid="qui-tab-navigation-rail"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-tab-navigation-rail {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: var(--border-width-default);
  background-color: var(--color-border);
  margin: 0;
  padding: 0;
}
</style>

// packages/angular/src/components/tab-navigation/tab-navigation-rail.component.ts
import { CdkMenuBar } from '@angular/cdk/menu';
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-tab-navigation-rail]',
  template: ` <ng-content></ng-content> `,
  hostDirectives: [CdkMenuBar],
  host: {
    'data-testid': 'tab-navigation__rail',
  },
  styles: [
    `
      :host {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: var(--border-width-default);
        background-color: var(--color-border);
        margin: 0;
        padding: 0;
      }
    `,
  ],
  standalone: true,
})
export class TabNavigationRailComponent {}
