// packages/angular/src/components/dropdown-menu/dropdown-menu-content.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-dropdown-menu-content]',
  template: `<ng-content></ng-content>`,
  standalone: true,
  host: {
    role: 'menu',
    'aria-orientation': 'vertical',
    'data-testid': 'qui-dropdown-menu-content',
    tabindex: '-1',
  },
  styles: [
    `
      :host {
        z-index: var(--z-index-50);
        min-width: var(--spacing-32);
        width: var(--spacing-48);
        overflow: hidden;
        border-radius: var(--border-radius-default);
        border: var(--border-width-default) solid var(--color-border);
        background: var(--color-popover);
        padding: var(--spacing-1);
        color: var(--color-popover-fg);
        box-shadow: var(--box-shadow-lg);
      }
    `,
  ],
})
export class DropdownMenuContentComponent {}

// packages/vue/src/components/dropdown-menu/dropdown-menu-content.vue
<script setup lang="ts">
import { computed } from 'vue'
import { MenuContent as RekaMenuContent, MenuPortal } from 'reka-ui'

export interface DropdownMenuContentProps {
  sideOffset?: number
  forceMount?: boolean
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<DropdownMenuContentProps>(), {
  sideOffset: 4,
  forceMount: false,
  asChild: false,
  as: 'div'
})
</script>

<template>
  <MenuPortal>
    <RekaMenuContent
      :side-offset="sideOffset"
      :force-mount="forceMount"
      :as-child="asChild"
      :as="as"
      :class="['q-dropdown-menu-content']"
      v-bind="$attrs"
    >
      <slot />
    </RekaMenuContent>
  </MenuPortal>
</template>

<style scoped>
.q-dropdown-menu-content {
  z-index: var(--z-index-50);
  min-width: 8rem;
  overflow: hidden;
  border-radius: var(--border-radius-md);
  border: var(--border-width-default) solid var(--color-border);
  background-color: var(--color-popover);
  color: var(--color-popover-fg);
  padding: var(--spacing-1);
  box-shadow: var(--box-shadow-md);
}
</style>
