// packages/angular/src/components/dropdown-menu/dropdown-menu-item.component.ts
import { Component, ElementRef, HostListener } from '@angular/core';

@Component({
  selector: '[pui-dropdown-menu-item]',
  template: `<ng-content></ng-content>`,
  standalone: true,
  host: {
    role: 'menuitem',
    'data-testid': 'pui-dropdown-menu-item',
  },
  styles: [
    `
      :host {
        position: relative;
        display: flex;
        cursor: pointer;
        user-select: none;
        list-style: none;
        align-items: center;
        gap: var(--spacing-2);
        border-radius: var(--border-radius-sm);
        padding: var(--spacing-1-5) var(--spacing-2) var(--spacing-1-5) var(--spacing-2);
        font-size: var(--font-size-sm);
        outline: none;
        transition:
          background-color 0.2s,
          color 0.2s;
      }

      :host:hover {
        background-color: hsl(from var(--color-background) h s l / 66%);
      }

      :host(:focus) {
        background-color: var(--color-accent);
        color: var(--color-accent-foreground);
      }

      :host > svg {
        width: var(--size-4);
        height: var(--size-4);
        flex-shrink: 0;
      }
    `,
  ],
})
export class DropdownMenuItemComponent {
  constructor(private elementRef: ElementRef) {}

  @HostListener('keydown.space')
  @HostListener('keydown.enter')
  triggerClick() {
    this.elementRef.nativeElement.click();
  }

  @HostListener('keydown.arrowup')
  triggerArrowUp() {
    this.elementRef.nativeElement.previousElementSibling?.focus();
  }

  @HostListener('keydown.arrowdown')
  triggerArrowDown() {
    this.elementRef.nativeElement.nextElementSibling?.focus();
  }
}

// packages/vue/src/components/dropdown-menu/dropdown-menu-item.vue
<script setup lang="ts">
import { computed } from 'vue'
import { MenuItem as RekaMenuItem } from 'reka-ui'

export interface DropdownMenuItemProps {
  inset?: boolean
  disabled?: boolean
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<DropdownMenuItemProps>(), {
  inset: false,
  disabled: false,
  asChild: false,
  as: 'div'
})

const classes = computed(() => {
  return [
    'q-dropdown-menu-item',
    {
      'inset': props.inset
    }
  ]
})
</script>

<template>
  <RekaMenuItem
    :disabled="disabled"
    :as-child="asChild"
    :as="as"
    :class="classes"
    v-bind="$attrs"
  >
    <slot />
  </RekaMenuItem>
</template>

<style scoped>
.q-dropdown-menu-item {
  position: relative;
  display: flex;
  cursor: default;
  user-select: none;
  align-items: center;
  border-radius: var(--border-radius-sm);
  padding-left: var(--spacing-2);
  padding-right: var(--spacing-2);
  padding-top: var(--spacing-1-5);
  padding-bottom: var(--spacing-1-5);
  font-size: var(--font-size-sm);
  outline: none;
  transition: colors 0.3s;
}

.q-dropdown-menu-item:focus {
  background-color: var(--color-muted);
  color: var(--color-muted-fg);
}

.q-dropdown-menu-item[data-disabled] {
  pointer-events: none;
  opacity: 0.5;
}

.q-dropdown-menu-item.inset {
  padding-left: var(--spacing-8);
}
</style>
