// packages/angular/src/components/header/header-content.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-header-content]',
  standalone: true,
  host: {
    'data-testid': 'qui-header-content',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        margin: 0 auto;
        display: flex;
        flex-direction: column;
        max-width: var(--breakpoint-4xl);
        gap: var(--spacing-7);
      }
    `,
  ],
})
export class HeaderContentComponent {}

// packages/vue/src/components/header/header-content.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeaderContentProps {
  as?: "div";
  asChild?: boolean;
}

const props = withDefaults(defineProps<HeaderContentProps>(), {
  as: "div",
  asChild: false,
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-header-content']"
    data-testid="qui-header-content"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  max-width: var(--columns-4xl);
  gap: var(--spacing-7);
}
</style>
