// packages/angular/src/components/drawer/drawer.component.ts
import { AsyncPipe, NgTemplateOutlet } from '@angular/common';
import {
  Component,
  ContentChild,
  ElementRef,
  HostListener,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
  TemplateRef,
} from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { DrawerOverlayComponent } from './drawer-overlay.component';

export type DrawerVariants = {
  variant: 'side' | 'over' | 'push';
  position: 'left' | 'right';
  hasBackdrop: boolean | 'auto';
};

@Component({
  selector: '[qui-drawer]',
  host: {
    'data-testid': 'drawer',
    '[class]': 'getClassList()',
  },
  imports: [AsyncPipe, NgTemplateOutlet, DrawerOverlayComponent],
  template: `
    @let isOpen = this.isOpenSubject | async;
    <div
      qui-drawer-overlay
      [variant]="variant"
      [position]="position"
      [hasBackdrop]="hasBackdrop"
      [opened]="isOpen ?? false"
    >
      <ng-container *ngTemplateOutlet="drawerContent"></ng-container>
    </div>
    <ng-content select="[qui-drawer-content]"></ng-content>
  `,
  styles: [
    `
      /* stylelint-disable selector-pseudo-class-no-unknown */
      :host {
        --drawer-width: 172px;

        position: relative;
        display: flex;
        height: 100svh;
        transition: width 0.3s ease;
      }

      :host-context(.open.has-backdrop) {
        background: hsl(from var(--color-muted) h s l / 33%);
      }

      :host :ng-deep [qui-drawer-content] {
        width: 100%;
        transition: margin 0.3s ease, width 0.3s ease;
      }

      :host-context(.variant--over.open) {
        width: var(--drawer-width);
      }

      :host-context(.variant--push.position--left)
        :ng-deep
        [qui-drawer-content]:not(.open) {
        margin-left: calc(-1 * var(--drawer-width));
      }

      :host-context(.variant--push.position--right)
        :ng-deep
        [qui-drawer-content]:not(.open) {
        margin-right: calc(-1 * var(--drawer-width));
      }

      /* stylelint-disable no-descending-specificity */
      :host-context(.has-backdrop.open) :ng-deep [qui-drawer-content] {
        pointer-events: none;
        opacity: 0.5;
      }
    `,
  ],
  standalone: true,
})
export class DrawerComponent implements OnInit, OnChanges {
  @Input() hasBackdrop: DrawerVariants['hasBackdrop'] = 'auto';
  @Input() variant: DrawerVariants['variant'] = 'over';
  @Input() position: DrawerVariants['position'] = 'left';
  @Input() opened: boolean | null = null;
  @ContentChild('drawerContent') drawerContent!: TemplateRef<unknown>;
  isOpenSubject = new BehaviorSubject<boolean>(false);

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    if (this.opened !== null) {
      this.isOpenSubject.next(this.opened);
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['opened']) {
      this.isOpenSubject.next(this.opened ?? false);
    }
  }

  open() {
    this.isOpenSubject.next(true);
  }

  close() {
    this.isOpenSubject.next(false);
  }

  toggle() {
    this.isOpenSubject.next(!this.isOpenSubject.value);
  }

  getHasBackdrop() {
    if (this.variant === 'side') {
      return false;
    }
    return this.isOpenSubject.value;
  }

  getClassList() {
    return {
      'has-backdrop': this.getHasBackdrop(),
      'variant--side': this.variant === 'side',
      'variant--over': this.variant === 'over',
      'variant--push': this.variant === 'push',
      'position--left': this.position === 'left',
      'position--right': this.position === 'right',
      open: this.isOpenSubject.value,
    };
  }

  getOverlayClassList() {
    return {
      drawer__overlay: true,
      ...this.getClassList(),
    };
  }

  getContentClassList() {
    return {
      drawer__content: true,
      ...this.getClassList(),
    };
  }

  @HostListener('document:keydown.escape')
  handleEscape() {
    this.close();
  }

  @HostListener('document:click', ['$event'])
  handleClick(event: MouseEvent) {
    if (this.variant === 'side') {
      return;
    }
    if (
      this.isOpenSubject.value &&
      this.elementRef.nativeElement === event.target
    ) {
      this.close();
    }
  }
}

// packages/vue/src/components/drawer/drawer.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted, onUnmounted } from "vue";
import { cva, type VariantProps } from "class-variance-authority";
import { Primitive } from "reka-ui";
import DrawerOverlay from "./drawer-overlay.vue";

const drawerVariants = cva("q-drawer", {
  variants: {
    variant: {
      side: "variant--side",
      over: "variant--over",
      push: "variant--push",
    },
    position: {
      left: "position--left",
      right: "position--right",
    },
  },
  defaultVariants: {
    variant: "over",
    position: "left",
  },
});

export type DrawerVariants = VariantProps<typeof drawerVariants>;

export interface DrawerProps {
  variant?: DrawerVariants["variant"];
  position?: DrawerVariants["position"];
  hasBackdrop?: boolean | "auto";
  opened?: boolean | null;
  defaultOpened?: boolean;
}

const props = withDefaults(defineProps<DrawerProps>(), {
  variant: "over",
  position: "left",
  hasBackdrop: "auto",
  opened: null,
  defaultOpened: false,
});

const emit = defineEmits<{
  "update:opened": [value: boolean];
}>();

const internalOpen = ref(props.defaultOpened);
const isControlled = computed(() => props.opened !== null);
const isOpen = computed(() =>
  isControlled.value ? props.opened ?? false : internalOpen.value
);

const classes = computed(() => {
  return drawerVariants({
    variant: props.variant,
    position: props.position,
  });
});

const drawerClasses = computed(() => {
  const hasBackdropValue = getHasBackdrop();
  return [
    classes.value,
    {
      open: isOpen.value,
      "has-backdrop": hasBackdropValue,
    },
  ];
});

const getHasBackdrop = () => {
  if (props.variant === "side") {
    return false;
  }
  if (props.hasBackdrop === "auto") {
    return isOpen.value;
  }
  return props.hasBackdrop;
};

const open = () => {
  if (isControlled.value) {
    emit("update:opened", true);
  } else {
    internalOpen.value = true;
  }
};

const close = () => {
  if (isControlled.value) {
    emit("update:opened", false);
  } else {
    internalOpen.value = false;
  }
};

const toggle = () => {
  if (isOpen.value) {
    close();
  } else {
    open();
  }
};

const handleEscape = (event: KeyboardEvent) => {
  if (event.key === "Escape" && isOpen.value) {
    close();
  }
};

const handleClick = (event: MouseEvent) => {
  if (props.variant === "side") {
    return;
  }
  if (isOpen.value && (event.target as HTMLElement) === event.currentTarget) {
    close();
  }
};

watch(
  () => props.opened,
  (newValue) => {
    if (isControlled.value && newValue !== null) {
      internalOpen.value = newValue;
    }
  }
);

onMounted(() => {
  document.addEventListener("keydown", handleEscape);
});

onUnmounted(() => {
  document.removeEventListener("keydown", handleEscape);
});

defineExpose({
  open,
  close,
  toggle,
  isOpen,
});
</script>

<template>
  <Primitive
    :as="'div'"
    :class="drawerClasses"
    @click="handleClick"
    v-bind="$attrs"
    data-testid="qui-drawer"
  >
    <DrawerOverlay
      :variant="variant"
      :position="position"
      :has-backdrop="getHasBackdrop()"
      :opened="isOpen"
    >
      <slot name="overlay" />
    </DrawerOverlay>
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  --drawer-width: 172px;

  position: relative;
  display: flex;
  height: 100svh;
  transition: width 0.3s ease;
}

.open.has-backdrop {
  background: hsl(from var(--color-muted) h s l / 33%);
}

.variant--over.open {
  width: var(--drawer-width);
}

.variant--push.position--left:not(.open) :deep(.q-drawer-content) {
  margin-left: calc(-1 * var(--drawer-width));
}

.variant--push.position--right:not(.open) :deep(.q-drawer-content) {
  margin-right: calc(-1 * var(--drawer-width));
}

.has-backdrop.open :deep(.q-drawer-content) {
  pointer-events: none;
  opacity: 0.5;
}
</style>
