// packages/angular/src/components/hero/hero-actions.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-hero-actions]',
  standalone: true,
  host: {
    'data-testid': 'qui-hero-actions',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: flex;
        gap: var(--spacing-8);
      }
    `,
  ],
})
export class HeroActionsComponent {}

// packages/vue/src/components/hero/hero-actions.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeroActionsProps {
  asChild?: boolean;
  as?: "div";
}

const props = withDefaults(defineProps<HeroActionsProps>(), {
  asChild: false,
  as: "div",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-hero-actions"
    data-testid="qui-hero-actions"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
  gap: var(--spacing-8);
}
</style>
