// packages/angular/src/components/hero/hero-backdrop.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-hero-backdrop]',
  standalone: true,
  host: {
    'data-testid': 'qui-hero-backdrop',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        position: relative;
        height: 100%;
        width: 100%;
      }
    `,
  ],
})
export class HeroBackdropComponent {}

// packages/vue/src/components/hero/hero-backdrop.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface HeroBackdropProps {
  asChild?: boolean;
  as?: "div";
}

const props = withDefaults(defineProps<HeroBackdropProps>(), {
  asChild: false,
  as: "div",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-hero-backdrop"
    data-testid="qui-hero-backdrop"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  position: relative;
  height: 100%;
  width: 100%;
}
</style>
