// packages/angular/src/components/autocomplete/autocomplete-group.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-autocomplete-group]',
  standalone: true,
  host: {
    'data-testid': 'qui-autocomplete-group',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        padding: var(--spacing-2);
        list-style: none;
        margin: 0;
      }
    `,
  ],
})
export class AutocompleteGroupComponent {}

// packages/vue/src/components/autocomplete/autocomplete-group.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface AutocompleteGroupProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<AutocompleteGroupProps>(), {
  asChild: false,
  as: 'ul'
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-autocomplete-group']"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-autocomplete-group {
  padding: var(--spacing-2);
  list-style: none;
  margin: 0;
}
</style>
