// packages/angular/src/components/autocomplete/autocomplete-trigger.component.ts
import {
  Component,
  EventEmitter,
  HostListener,
  Input,
  Output,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { AutocompleteComponent } from './autocomplete.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'div[qui-autocomplete-trigger]',
  standalone: true,
  host: {
    'data-testid': 'autocomplete__trigger',
  },
  imports: [CommonModule, FormsModule],
  template: `
    <input
      [(ngModel)]="searchValue"
      (ngModelChange)="handleInputChange()"
      placeholder="Search..."
    />
    <svg
      width="20"
      height="20"
      viewBox="0 0 15 15"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z"
        fill="currentColor"
        fill-rule="evenodd"
        clip-rule="evenodd"
      ></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: inline-flex;
        flex: 1 1 auto;
        position: relative;
        justify-content: space-between;
        border-radius: var(--border-radius-md);
        border: 1px solid var(--color-border);
        background-color: var(--color-input);
        color: var(--color-input-fg);
        font-size: var(--font-size-sm);
        line-height: var(--line-height-sm);
        cursor: pointer;
        padding: var(--spacing-3) var(--spacing-2);
      }
      :host input {
        width: 100%;
        border: none;
        outline: none;
        background-color: transparent;
        color: inherit;
        font-size: inherit;
        line-height: inherit;
      }
    `,
  ],
})
export class AutocompleteTriggerComponent {
  @Input() searchValue = '';
  @Output() valueChange = new EventEmitter<string>();

  constructor(protected autocomplete: AutocompleteComponent) {
    this.autocomplete.getSelectedOption$().subscribe((option) => {
      this.searchValue = option?.label || '';
      this.valueChange.emit(this.searchValue);
    });
  }

  handleInputChange() {
    this.valueChange.emit(this.searchValue);
  }

  @HostListener('click')
  toggleOpen() {
    this.autocomplete.popover.show();
  }
}

// packages/vue/src/components/autocomplete/autocomplete-trigger.vue
<script setup lang="ts">
import { inject, ref, watch, computed } from 'vue'
import { PopoverTrigger, PopoverAnchor } from 'reka-ui'
import { ChevronDown } from 'lucide-vue-next'
import InputComponent from '../input/input.vue'
import type { AutocompleteOption } from './autocomplete.vue'

export interface AutocompleteTriggerProps {
  searchValue?: string
  placeholder?: string
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<AutocompleteTriggerProps>(), {
  searchValue: '',
  placeholder: 'Search...',
  asChild: false,
  as: 'div'
})

const emit = defineEmits<{
  'update:searchValue': [value: string]
  'valueChange': [value: string]
}>()

const autocompleteContext = inject<{
  isOpen: ReturnType<typeof computed<boolean>>
  open: () => void
  close: () => void
  toggle: () => void
  selectedOption: ReturnType<typeof computed<AutocompleteOption | null>>
  getSelectedOption: () => AutocompleteOption | null
}>('autocompleteContext')

if (!autocompleteContext) {
  throw new Error('AutocompleteTrigger must be used within Autocomplete')
}

const internalSearchValue = ref(props.searchValue)

// Watch for selected option changes
watch(
  () => autocompleteContext.selectedOption.value,
  (option) => {
    if (option) {
      internalSearchValue.value = option.label
      emit('update:searchValue', option.label)
      emit('valueChange', option.label)
    }
  },
  { immediate: true }
)

// Watch for external searchValue changes
watch(
  () => props.searchValue,
  (newValue) => {
    if (newValue !== undefined) {
      internalSearchValue.value = newValue
    }
  }
)

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  internalSearchValue.value = target.value
  emit('update:searchValue', target.value)
  emit('valueChange', target.value)
  autocompleteContext.open()
}

const handleClick = () => {
  autocompleteContext.toggle()
}
</script>

<template>
  <PopoverAnchor :as-child="asChild" :as="as" :class="['q-autocomplete-trigger']" v-bind="$attrs">
    <PopoverTrigger
      :as-child="true"
      :as="'div'"
      :class="['q-autocomplete-trigger-wrapper']"
      @click="handleClick"
    >
      <InputComponent
        v-model="internalSearchValue"
        :placeholder="placeholder"
        @input="handleInput"
        @click.stop
        class="q-autocomplete-trigger-input"
      />
      <ChevronDown :size="20" :class="['q-autocomplete-trigger-icon']" aria-hidden="true" />
    </PopoverTrigger>
  </PopoverAnchor>
</template>

<style scoped>
.q-autocomplete-trigger {
  display: inline-flex;
  flex: 1 1 auto;
  position: relative;
}

.q-autocomplete-trigger-wrapper {
  display: inline-flex;
  flex: 1 1 auto;
  position: relative;
  justify-content: space-between;
  align-items: center;
  border-radius: var(--border-radius-md);
  border: var(--border-width-default) solid var(--color-border);
  background-color: var(--color-input);
  color: var(--color-input-fg);
  font-size: var(--font-size-sm);
  line-height: var(--line-height-sm);
  cursor: pointer;
  padding: var(--spacing-3) var(--spacing-2);
  gap: var(--spacing-2);
}

.q-autocomplete-trigger-input {
  flex: 1;
  border: none;
  outline: none;
  background-color: transparent;
  padding: 0;
}

.q-autocomplete-trigger-input :deep(input) {
  border: none;
  padding: 0;
  background-color: transparent;
}

.q-autocomplete-trigger-icon {
  flex-shrink: 0;
  color: var(--color-muted-fg);
  transition: transform 0.2s;
}

.q-autocomplete-trigger-wrapper[data-state='open'] .q-autocomplete-trigger-icon {
  transform: rotate(180deg);
}
</style>
