// packages/angular/src/components/footer/footer-content.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-footer-content]',
  standalone: true,
  host: {
    'data-testid': 'qui-footer-content',
  },
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        gap: var(--spacing-10);
      }

      @media (width >= 768px) {
        :host {
          gap: var(--spacing-14);
        }
      }

      @media (width >= 1280px) {
        :host {
          flex-direction: row;
        }
      }
    `,
  ],
})
export class FooterContentComponent {}

// packages/vue/src/components/footer/footer-content.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface FooterContentProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<FooterContentProps>(), {
  asChild: false,
});

const footerContentClasses = computed(() => ["q-footer-content"]);
</script>

<template>
  <Primitive
    as="div"
    :as-child="asChild"
    :class="footerContentClasses"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: var(--spacing-10);
}

@media (width >= 768px) {
  div {
    gap: var(--spacing-14);
  }
}

@media (width >= 1280px) {
  div {
    flex-direction: row;
  }
}
</style>
