// packages/angular/src/components/chat-message/chat-message-bubble-text.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-chat-message-bubble-text]',
  template: ` <ng-content></ng-content> `,
  host: {
    'data-testid': 'qui-chat-message-bubble-text',
  },
  styles: [
    `
      :host {
        font-size: var(--font-size-sm);
        font-weight: var(--font-weight-normal);
        line-height: var(--line-height-snug);
        margin: 0;
      }
    `,
  ],
  standalone: true,
})
export class ChatMessageBubbleTextComponent {}

// packages/vue/src/components/chat-message/chat-message-bubble-text.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface ChatMessageBubbleTextProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<ChatMessageBubbleTextProps>(), {
  asChild: false,
  as: 'h5'
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-chat-message-bubble-text']"
    data-testid="qui-chat-message-bubble-text"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-chat-message-bubble-text {
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-normal);
  line-height: var(--line-height-snug);
  margin: 0;
}
</style>
