// packages/vue/src/components/tree/tree-item.vue
<script setup lang="ts">
import { computed, ref, useSlots } from "vue";
import Collapsible from "../collapsible/collapsible.vue";
import CollapsibleTrigger from "../collapsible/collapsible-trigger.vue";
import CollapsibleContent from "../collapsible/collapsible-content.vue";
import TreeItemIndicator from "./tree-item-indicator.vue";

export interface TreeItemProps {
  expanded?: boolean;
  defaultExpanded?: boolean;
}

const props = withDefaults(defineProps<TreeItemProps>(), {
  expanded: undefined,
  defaultExpanded: false,
});

const emit = defineEmits<{
  "update:expanded": [value: boolean];
}>();

const slots = useSlots();
const isOpen = ref(props.defaultExpanded);

const hasGroups = computed(() => {
  return !!slots.default;
});

const isExpanded = computed(() => {
  return props.expanded !== undefined ? props.expanded : isOpen.value;
});

const handleOpenChange = (open: boolean) => {
  if (props.expanded === undefined) {
    isOpen.value = open;
  }
  emit("update:expanded", open);
};

const handleKeydown = (event: KeyboardEvent) => {
  if (event.key === "Enter") {
    event.preventDefault();
    handleOpenChange(!isExpanded.value);
  }
};
</script>

<template>
  <div class="q-tree-item">
    <Collapsible
      :open="isExpanded"
      @update:open="handleOpenChange"
      role="treeitem"
      :aria-expanded="isExpanded"
      aria-selected="false"
    >
      <CollapsibleTrigger as="div" class="q-tree-item-trigger-wrapper">
        <div
          role="button"
          data-testid="qui-tree-item-trigger"
          class="q-tree-item-trigger"
          tabindex="0"
          @keydown="handleKeydown"
        >
          <TreeItemIndicator
            :empty="!hasGroups"
            :expanded="isExpanded"
          />
          <slot name="icon" />
          <slot name="label" />
        </div>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <slot />
      </CollapsibleContent>
    </Collapsible>
  </div>
</template>

<style scoped>
.q-tree-item {
  display: flex;
  align-items: center;
  cursor: pointer;
}

.q-tree-item-trigger-wrapper {
  width: 100%;
}

.q-tree-item-trigger {
  display: flex;
  align-items: center;
  width: 100%;
}

.q-tree-item-trigger:focus-visible {
  outline: none;
  box-shadow:
    0 0 0 2px var(--color-ring),
    0 0 0 4px var(--color-background);
}
</style>

// packages/angular/src/components/tree/tree-item.component.ts
import { CommonModule } from '@angular/common';
import { Component, ContentChildren, Input, QueryList } from '@angular/core';
import { CollapsibleComponent } from '../collapsible/collapsible.component';
import { TreeItemIndicatorComponent } from './tree-item-indicator.component';
import { TreeGroupComponent } from './tree-group.component';
import { CollapsibleTriggerComponent } from '../collapsible/collapsible-trigger.component';
import { CollapsibleContentComponent } from '../collapsible/collapsible-content.component';

@Component({
  selector: '[qui-tree-item]',
  standalone: true,
  host: {
    'data-testid': 'tree__item',
  },
  imports: [
    CommonModule,
    CollapsibleComponent,
    TreeItemIndicatorComponent,
    CollapsibleTriggerComponent,
    CollapsibleContentComponent,
  ],
  template: `
    <div
      qui-collapsible
      [expanded]="expanded"
      role="treeitem"
      [attr.aria-expanded]="expanded"
      [attr.aria-selected]="false"
    >
      <div qui-collapsible-trigger>
        <div
          role="button"
          data-testid="tree__item-trigger"
          class="tree-item"
          (click)="handleClick()"
          (keydown)="handleKeydown($event)"
          tabindex="0"
        >
          <qui-tree-item-indicator
            [empty]="!hasGroups()"
            [expanded]="expanded"
          ></qui-tree-item-indicator>
          <ng-content select="[qui-tree-item-icon]"></ng-content>
          <ng-content select="[qui-tree-item-label]"></ng-content>
        </div>
      </div>
      <ng-template #content>
        <div qui-collapsible-content>
          <ng-content select="[qui-tree-group]"></ng-content>
        </div>
      </ng-template>
    </div>
  `,
  styles: [
    `
      :host {
        display: flex;
        align-items: center;
        cursor: pointer;
      }

      .tree-item {
        display: flex;
        align-items: center;
      }
    `,
  ],
})
export class TreeItemComponent {
  @Input() expanded = false;
  @ContentChildren(TreeGroupComponent, { descendants: true })
  groups: QueryList<TreeGroupComponent> = new QueryList<TreeGroupComponent>();

  hasGroups() {
    return this.groups.length > 0;
  }

  handleClick() {
    this.expanded = !this.expanded;
  }

  handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.expanded = !this.expanded;
    }
  }
}
