// packages/vue/src/components/tree/tree-item-indicator.vue
<script setup lang="ts">
import { ChevronDown, ChevronRight } from "lucide-vue-next";

export interface TreeItemIndicatorProps {
  expanded?: boolean;
  empty?: boolean;
}

const props = withDefaults(defineProps<TreeItemIndicatorProps>(), {
  expanded: false,
  empty: false,
});
</script>

<template>
  <div
    v-if="!empty"
    data-testid="qui-tree-item-indicator"
    class="q-tree-item-indicator"
  >
    <ChevronDown v-if="expanded" :size="16" />
    <ChevronRight v-else :size="16" />
  </div>
  <div v-else class="q-tree-item-indicator q-tree-item-indicator--empty" />
</template>

<style scoped>
.q-tree-item-indicator {
  margin-right: var(--spacing-2);
  display: inline-flex;
  align-items: center;
  color: var(--color-background-fg);
}

.q-tree-item-indicator--empty {
  display: inline-block;
  width: var(--spacing-4);
  height: var(--spacing-4);
}
</style>

// packages/angular/src/components/tree/tree-item-indicator.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import {
  IconChevronDownComponent,
  IconChevronRightComponent,
} from '../../icons';

@Component({
  selector: 'qui-tree-item-indicator',
  standalone: true,
  host: {
    'data-testid': 'qui-tree-item-indicator',
  },
  imports: [IconChevronRightComponent, IconChevronDownComponent, CommonModule],
  template: `<ng-container *ngIf="!empty; else noContent">
      <ng-container *ngIf="expanded; else collapsed">
        <i qui-icon name="chevron-down"></i>
      </ng-container>
      <ng-template #collapsed>
        <i qui-icon name="chevron-right"></i>
      </ng-template>
    </ng-container>
    <ng-template #noContent>
      <div class="empty"></div>
    </ng-template> `,
  styles: [
    `
      :host {
        margin-right: var(--spacing-2);
      }

      :host .empty {
        display: inline-block;
        width: var(--spacing-4);
        height: var(--spacing-4);
      }
    `,
  ],
})
export class TreeItemIndicatorComponent {
  @Input() expanded = false;
  @Input() empty = false;
}
