// packages/vue/src/components/navigation-menu/navigation-menu-link.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface NavigationMenuLinkProps {
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<NavigationMenuLinkProps>(), {
  asChild: false,
  as: "a",
});

const classes = computed(() => ["q-navigation-menu-link"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    data-testid="qui-navigation-menu-link"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
a {
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-semibold);
  line-height: var(--line-height-6);
  color: var(--color-background-fg);
}

a:visited {
  color: var(--color-background-fg);
}

a:link {
  color: var(--color-background-fg);
}

a:hover {
  background-color: var(--color-muted);
}
</style>

// packages/angular/src/components/navigation-menu/navigation-menu-link.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'a[qui-navigation-menu-link]',
  host: {
    'data-testid': 'qui-navigation-menu-link',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        font-size: var(--font-size-sm);
        font-weight: var(--font-weight-semibold);
        line-height: var(--line-height-6);
        color: var(--color-background-fg);
      }

      :host:visited {
        color: var(--color-background-fg);
      }

      :host:link {
        color: var(--color-background-fg);
      }

      :host(:hover) {
        background-color: var(--color-muted);
      }
    `,
  ],
  standalone: true,
})
export class NavigationMenuLinkComponent {}
