// packages/vue/src/components/navigation-menu/navigation-menu-brand.vue
<script setup lang="ts">
import { computed } from "vue";
import { Primitive } from "reka-ui";

export interface NavigationMenuBrandProps {
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<NavigationMenuBrandProps>(), {
  asChild: false,
  as: "div",
});

const classes = computed(() => ["q-navigation-menu-brand"]);
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    data-testid="qui-navigation-menu-brand"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
}
</style>

// packages/angular/src/components/navigation-menu/navigation-menu-brand.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-navigation-menu-brand]',
  host: {
    'data-testid': 'qui-navigation-menu-brand',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        display: flex;
      }
    `,
  ],
  standalone: true,
})
export class NavigationMenuBrandComponent {}
