// packages/react/src/components/vstack/vstack.tsx
import React from "react";
import styled, { css } from "styled-components";
import { cva, type VariantProps } from "class-variance-authority";

const vstackVariants = cva("q-vstack", {
  variants: {
    gap: {
      none: "gap--none",
      sm: "gap--sm",
      md: "gap--md",
      lg: "gap--lg",
      xl: "gap--xl",
      "2xl": "gap--2xl",
    },
  },
  defaultVariants: {
    gap: "md",
  },
});

const vstackStyles = css`
  display: flex;
  flex-direction: column;

  &.gap--none {
    gap: 0;
  }

  &.gap--sm {
    gap: var(--spacing-2);
  }

  &.gap--md {
    gap: var(--spacing-4);
  }

  &.gap--lg {
    gap: var(--spacing-6);
  }

  &.gap--xl {
    gap: var(--spacing-8);
  }

  &.gap--2xl {
    gap: var(--spacing-12);
  }
`;

const StyledVStack = styled.div`
  ${vstackStyles}
`;

export type VStackProps = React.ComponentPropsWithoutRef<"div"> &
  VariantProps<typeof vstackVariants>;

export const VStack = React.forwardRef<HTMLDivElement, VStackProps>(
  ({ children, className, gap, ...props }, ref) => {
    return (
      <StyledVStack
        data-testid="vstack"
        ref={ref}
        className={vstackVariants({ gap, className })}
        {...props}
      >
        {children}
      </StyledVStack>
    );
  }
);
VStack.displayName = "VStack";

// packages/vue/src/components/vstack/vstack.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'
import { cva, type VariantProps } from 'class-variance-authority'

const vstackVariants = cva('q-vstack', {
  variants: {
    gap: {
      none: 'gap--none',
      sm: 'gap--sm',
      md: 'gap--md',
      lg: 'gap--lg',
      xl: 'gap--xl',
      '2xl': 'gap--2xl'
    }
  },
  defaultVariants: {
    gap: 'md'
  }
})

export type VStackVariants = VariantProps<typeof vstackVariants>

export interface VStackProps {
  gap?: VStackVariants['gap']
  as?: string
  asChild?: boolean
}

const props = withDefaults(defineProps<VStackProps>(), {
  gap: 'md',
  asChild: false,
  as: 'div'
})

const classes = computed(() => {
  return vstackVariants({
    gap: props.gap
  })
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  display: flex;
  flex-direction: column;
}

.gap--none {
  gap: 0;
}

.gap--sm {
  gap: var(--spacing-2);
}

.gap--md {
  gap: var(--spacing-4);
}

.gap--lg {
  gap: var(--spacing-6);
}

.gap--xl {
  gap: var(--spacing-8);
}

.gap--2xl {
  gap: var(--spacing-12);
}
</style>
