// packages/angular/src/components/spotlight-gallery/spotlight-gallery-image.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'img[qui-spotlight-gallery-image]',
  standalone: true,
  host: {
    'data-testid': 'qui-spotlight-gallery-image',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        width: 100%;
        aspect-ratio: 1;
      }
    `,
  ],
})
export class SpotlightGalleryImageComponent {}

// packages/vue/src/components/spotlight-gallery/spotlight-gallery-image.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'
</script>

<template>
  <Primitive
    as="img"
    :class="['q-spotlight-gallery-image']"
    data-testid="qui-spotlight-gallery-image"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-spotlight-gallery-image {
  width: 100%;
  aspect-ratio: 1;
}
</style>
