// packages/vue/src/components/file-input/file-input.vue
<script setup lang="ts">
import { ref } from 'vue'
import ButtonComponent from '@/components/button/button.vue'
import { File, X } from 'lucide-vue-next'

export interface FileInputProps {
  multiple?: boolean
}

const props = withDefaults(defineProps<FileInputProps>(), {
  multiple: false
})

const emit = defineEmits<{
  filesSelected: [files: File[]]
}>()

const files = ref<File[]>([])
const inputRef = ref<HTMLInputElement | null>(null)

const handleClick = () => {
  if (inputRef.value) {
    inputRef.value.click()
  }
}

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Enter') {
    handleClick()
  }
}

const handleChange = (event: Event) => {
  const input = event.target as HTMLInputElement
  if (input.files) {
    files.value = Array.from(input.files)
    emit('filesSelected', files.value)
  }
}

const handleClear = (event: Event) => {
  event.stopPropagation()
  files.value = []
  if (inputRef.value) {
    inputRef.value.value = ''
  }
  emit('filesSelected', files.value)
}
</script>

<template>
  <div
    class="q-file-input"
    @click="handleClick"
    tabindex="0"
    @keydown="handleKeyDown"
    data-testid="qui-file-input"
  >
    <input
      ref="inputRef"
      data-testid="qui-file-input-input"
      type="file"
      class="hidden"
      :multiple="multiple"
      @change="handleChange"
    />
    <File :size="16" />
    <span v-if="files.length > 0">{{ files.length }} file(s) selected</span>
    <span v-else class="placeholder">Choose a file...</span>
    <ButtonComponent
      v-if="files.length > 0"
      class="clear-button"
      variant="ghost"
      size="icon"
      @click="handleClear"
    >
      <X :size="16" />
    </ButtonComponent>
  </div>
</template>

<style scoped>
.q-file-input {
  display: inline-flex;
  align-items: center;
  border: 1px solid var(--color-border);
  border-radius: var(--border-radius-md);
  padding: var(--spacing-2);
  cursor: pointer;
  gap: var(--spacing-1);
}

.q-file-input svg {
  margin-right: var(--spacing-1);
  width: var(--spacing-4);
  height: var(--spacing-4);
  flex-shrink: 0;
}

.q-file-input span {
  font-size: var(--font-size-sm);
  line-height: var(--line-height-sm);
}

.q-file-input .placeholder {
  color: var(--color-muted-fg);
}

.q-file-input:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--color-ring), 0 0 0 4px var(--color-background);
}

.hidden {
  display: none;
}

.clear-button {
  margin-left: var(--spacing-2);
}
</style>

// packages/angular/src/components/file-input/file-input.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import { ButtonComponent } from '../button/button.component';
import { IconCross2Component } from '../../icons';
import { IconFileComponent } from '../../icons';

@Component({
  selector: 'qui-file-input',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    IconFileComponent,
    IconCross2Component,
  ],
  template: `
    <div
      class="file-input"
      (click)="handleClick()"
      tabindex="0"
      (keydown)="handleKeyDown($event)"
      data-testid="qui-file-input"
    >
      <input
        #input
        data-testid="qui-file-input-input"
        type="file"
        class="hidden"
        (change)="handleChange($event)"
        [attr.multiple]="multiple ? '' : null"
      />
      <i qui-icon name="file" size="sm"></i>
      <span *ngIf="files.length > 0">{{ files.length }} file(s) selected</span>
      <span *ngIf="files.length === 0" class="placeholder"
        >Choose a file...</span
      >
      <button
        class="clear-button"
        qui-button
        variant="ghost"
        size="icon"
        *ngIf="files.length > 0"
        (click)="handleClear($event)"
      >
        <i qui-icon name="cross-2" size="sm"></i>
      </button>
    </div>
  `,
  styles: [
    `
      .file-input {
        display: inline-flex;
        align-items: center;
        border: 1px solid var(--color-border);
        border-radius: var(--border-radius-md);
        padding: var(--spacing-2);
        cursor: pointer;
      }

      .file-input i {
        margin-right: var(--spacing-1);
        width: var(--spacing-4);
        height: var(--spacing-4);
      }

      .file-input span {
        font-size: var(--font-size-sm);
        line-height: var(--line-height-sm);
      }

      .file-input .placeholder {
        color: var(--color-muted-fg);
      }

      .hidden {
        display: none;
      }

      .clear-button.size--icon {
        margin-left: var(--spacing-2);
        width: var(--spacing-5);
        height: var(--spacing-5);
        cursor: pointer;
      }
    `,
  ],
})
export class FileInputComponent {
  @Input() multiple = false;
  @Output() filesSelected = new EventEmitter<File[]>();
  @ViewChild('input') input!: ElementRef;
  files: File[] = [];

  constructor(private elementRef: ElementRef) {}

  handleClick() {
    this.input.nativeElement.click();
  }

  handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.handleClick();
    }
  }

  handleChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files) {
      this.files = Array.from(input.files);
      this.filesSelected.emit(this.files);
    }
  }

  handleClear(event: Event) {
    event.stopPropagation();
    this.files = [];
    this.input.nativeElement.value = '';
    this.filesSelected.emit(this.files);
  }
}
