// packages/angular/src/components/textarea/textarea.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

export type TextareaVariants = {
  size: 'sm' | 'md' | 'lg';
};

@Component({
  selector: 'textarea[qui-textarea]',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  host: {
    '[class]': 'getClassList()',
    'data-testid': 'qui-textarea',
  },
  styles: [
    `
      :host {
        display: flex;
        min-height: 80px;
        width: 100%;
        border-radius: var(--border-radius-md);
        border: 1px solid var(--color-input);
        background-color: var(--color-input);
        color: var(--color-input-fg);

        &::placeholder {
          color: var(--color-muted-fg);
        }

        &:focus-visible {
          outline: none;
          border-color: var(--color-ring);
        }

        &:disabled {
          cursor: not-allowed;
          opacity: 0.5;
        }
      }

      :host-context(.size--sm) {
        font-size: var(--font-size-xs);
        padding: var(--spacing-2) var(--spacing-3);
      }

      :host-context(.size--md) {
        font-size: var(--font-size-sm);
        padding: var(--spacing-3) var(--spacing-2);
      }

      :host-context(.size--lg) {
        font-size: var(--font-size-md);
        padding: var(--spacing-4) var(--spacing-3);
      }
    `,
  ],
})
export class TextareaComponent {
  @Input() size: TextareaVariants['size'] = 'md';

  getClassList(): string {
    return `size--${this.size}`;
  }
}

// packages/react/src/components/textarea/textarea.tsx
import React from "react";
import styled from "styled-components";

const StyledTextarea = styled.textarea`
  display: flex;
  min-height: 80px;
  width: 100%;
  border-radius: var(--border-radius-md);
  border: var(--border-width-default) solid var(--color-border);
  background-color: var(--color-input);
  color: var(--color-input-fg);
  padding-left: var(--spacing-3);
  padding-right: var(--spacing-3);
  padding-top: var(--spacing-2);
  padding-bottom: var(--spacing-2);
  font-size: var(--font-size-sm);
  box-shadow: 0 0 0 0 var(--color-background);

  &::placeholder {
    color: var(--color-muted-fg);
  }

  &:focus-visible {
    outline: none;
    box-shadow: 0 0 0 2px var(--color-ring), 0 0 0 4px var(--color-background);
  }

  &:disabled {
    cursor: not-allowed;
    opacity: 0.5;
  }
`;

export type TextareaProps = React.TextareaHTMLAttributes<HTMLTextAreaElement>;

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, ...props }, ref) => {
    return <StyledTextarea className={className} ref={ref} {...props} />;
  }
);
Textarea.displayName = "Textarea";
