// packages/vue/src/components/drawer/drawer-content.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";
</script>

<template>
  <Primitive
    :as="'div'"
    class="q-drawer-content"
    v-bind="$attrs"
    data-testid="drawer__content"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-drawer-content {
  width: 100%;
  transition: margin 0.3s ease, width 0.3s ease;
}
</style>

// packages/angular/src/components/drawer/drawer-content.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-drawer-content]',
  standalone: true,
  host: {
    'data-testid': 'drawer__content',
    '[class]': 'getClassList()',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      .drawer__content {
        width: 100%;
        transition: margin 0.3s ease, width 0.3s ease;
      }
    `,
  ],
})
export class DrawerContentComponent {
  getClassList() {
    return {
      drawer__content: true,
    };
  }
}
