// packages/vue/src/components/breadcrumb/breadcrumb-item.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface BreadcrumbItemProps {
  asChild?: boolean;
}

const props = withDefaults(defineProps<BreadcrumbItemProps>(), {
  asChild: false,
});
</script>

<template>
  <Primitive
    as="li"
    :as-child="asChild"
    data-testid="qui-breadcrumb-item"
    class="q-breadcrumb-item"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
li {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-1-5);
}
</style>

// packages/angular/src/components/breadcrumb/breadcrumb-item.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'li[qui-breadcrumb-item]',
  standalone: true,
  host: {
    'data-testid': 'qui-breadcrumb-item',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        display: inline-flex;
        align-items: center;
        gap: var(--spacing-1-5);
      }
    `,
  ],
})
export class BreadcrumbItemComponent {}
