// packages/angular/src/components/carousel/carousel-content.component.ts
import { Component, Input, ElementRef, Renderer2 } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'div[pui-carousel-content]',
  template: `<ng-content></ng-content>`,
  host: {
    'data-testid': 'pui-carousel-content',
  },
  styles: [
    `
      :host {
        display: flex;
        transition: transform 0.3s ease;
        width: 100%;
      }
    `,
  ],
  standalone: true,
})
export class CarouselContentComponent {
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal';
  private currentIndex$ = new BehaviorSubject<number>(0);

  constructor(
    private el: ElementRef,
    private renderer: Renderer2,
  ) {}

  scrollPrev() {
    const currentIndex = this.currentIndex$.getValue();
    if (currentIndex > 0) {
      this.currentIndex$.next(currentIndex - 1);
      this.updateCarouselPosition();
    }
  }

  scrollNext() {
    const currentIndex = this.currentIndex$.getValue();
    const maxIndex = this.el.nativeElement.children.length - 1;
    if (currentIndex < maxIndex) {
      this.currentIndex$.next(currentIndex + 1);
      this.updateCarouselPosition();
    }
  }

  private updateCarouselPosition() {
    const currentIndex = this.currentIndex$.getValue();
    const offset = this.orientation === 'horizontal' ? 'translateX' : 'translateY';
    this.renderer.setStyle(this.el.nativeElement, 'transform', `${offset}(-${currentIndex * 100}%)`);
  }
}

// packages/vue/src/components/carousel/carousel-content.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref, watch } from 'vue'
import { Primitive } from 'reka-ui'

export interface CarouselContentProps {
  orientation?: 'horizontal' | 'vertical'
}

const props = withDefaults(defineProps<CarouselContentProps>(), {
  orientation: 'horizontal'
})

interface CarouselContext {
  orientation: 'horizontal' | 'vertical'
  currentIndex: { value: number }
  scrollPrev: () => void
  scrollNext: () => void
  updateIndex: (index: number) => void
  canScrollPrev: { value: boolean }
  canScrollNext: { value: boolean }
}

const carouselContext = inject<CarouselContext>('carousel')

if (!carouselContext) {
  throw new Error('CarouselContent must be used within a Carousel component')
}

const contentRef = ref<HTMLElement | null>(null)
const itemCount = ref(0)

const orientation = computed(() => props.orientation || carouselContext.orientation)

const updateCarouselPosition = () => {
  if (!contentRef.value) return

  const currentIndex = carouselContext.currentIndex.value
  const offset = orientation.value === 'horizontal' ? 'translateX' : 'translateY'
  contentRef.value.style.transform = `${offset}(-${currentIndex * 100}%)`

  // Update can scroll states
  carouselContext.canScrollPrev.value = currentIndex > 0
  carouselContext.canScrollNext.value = currentIndex < itemCount.value - 1
}

const scrollPrev = () => {
  if (carouselContext.currentIndex.value > 0) {
    carouselContext.currentIndex.value--
    updateCarouselPosition()
  }
}

const scrollNext = () => {
  if (carouselContext.currentIndex.value < itemCount.value - 1) {
    carouselContext.currentIndex.value++
    updateCarouselPosition()
  }
}

// Override the context methods with local implementations
carouselContext.scrollPrev = scrollPrev
carouselContext.scrollNext = scrollNext

onMounted(() => {
  if (contentRef.value) {
    itemCount.value = contentRef.value.children.length
    updateCarouselPosition()
  }
})

watch(() => carouselContext.currentIndex.value, () => {
  updateCarouselPosition()
})
</script>

<template>
  <Primitive
    as="div"
    ref="contentRef"
    :class="['q-carousel-content']"
    :data-orientation="orientation"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-carousel-content {
  display: flex;
  transition: transform 0.3s ease;
  width: 100%;
}

.q-carousel-content[data-orientation='vertical'] {
  flex-direction: column;
  height: 100%;
}
</style>
