// packages/angular/src/components/time-select/time-select.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnInit,
  SimpleChanges,
  OnChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'qui-time-select',
  standalone: true,
  imports: [CommonModule],
  host: {
    'data-testid': 'qui-time-select',
  },
  template: `
    <div class="time-select" data-testid="qui-time-select">
      <div
        class="time-column"
        #hourList
        data-testid="qui-time-select-hour-list"
      >
        <div
          *ngFor="let hour of displayHours"
          data-testid="qui-time-select-hour"
          (click)="handleClickHour(hour)"
          (keydown)="handleKeyDownHour($event)"
          tabindex="0"
          [class.selected]="hour === selectedHour"
          [attr.aria-selected]="hour === selectedHour"
        >
          {{ hour }}
        </div>
      </div>

      <div
        class="time-column"
        #minuteList
        data-testid="qui-time-select-minute-list"
      >
        <div
          *ngFor="let minute of displayMinutes"
          data-testid="qui-time-select-minute"
          (click)="handleClickMinute(minute)"
          (keydown)="handleKeyDownMinute($event)"
          tabindex="0"
          [class.selected]="minute === selectedMinute"
          [attr.aria-selected]="minute === selectedMinute"
        >
          {{ minute }}
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .time-select {
        display: flex;
        border: var(--border-width-default) solid var(--color-border);
        background-color: var(--color-background);
        border-radius: var(--border-radius-lg);
        padding: var(--spacing-4);
        width: var(--spacing-32);
      }
      .time-column {
        flex: 1;
        overflow-y: auto;
        height: 200px;
        scrollbar-width: thin;
        scrollbar-color: var(--color-border) transparent;
      }
      .time-column div {
        cursor: pointer;
        border-radius: var(--border-radius-md);
        padding: var(--spacing-2) var(--spacing-3);
        text-align: center;
        font-size: var(--font-size-sm);
      }
      .time-column div.selected {
        background-color: var(--color-primary);
        color: var(--color-primary-fg);
      }
      .time-column div:hover {
        background-color: var(--color-muted);
        color: var(--color-muted-fg);
      }
    `,
  ],
})
export class TimeSelectComponent implements AfterViewInit, OnInit, OnChanges {
  @Input() hours = '00';
  @Input() minutes = '00';
  @Output() valueHourChange = new EventEmitter<string>();
  @Output() valueMinuteChange = new EventEmitter<string>();
  @Output() valueChange = new EventEmitter<string>();

  @ViewChild('hourList') hourList!: ElementRef;
  @ViewChild('minuteList') minuteList!: ElementRef;

  displayHours: string[] = this.generateDefaultHours();
  displayMinutes: string[] = this.generateDefaultMinutes();

  private generateDefaultHours(): string[] {
    return Array.from({ length: 24 }, (_, i) => i.toString().padStart(2, '0'));
  }

  private generateDefaultMinutes(): string[] {
    return Array.from({ length: 12 }, (_, i) =>
      (i * 5).toString().padStart(2, '0')
    );
  }

  resetToDefault() {
    this.displayHours = this.generateDefaultHours();
    this.displayMinutes = this.generateDefaultMinutes();
  }

  ngAfterViewInit() {
    this.scrollToSelected(this.hours, this.hourList);
    this.scrollToSelected(this.minutes, this.minuteList);
  }

  ngOnInit() {
    this.addCurrentMinutes();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['selectedHour'] || changes['selectedMinute']) {
      this.resetToDefault();
      this.addCurrentMinutes();

      // Debounce scroll to selected
      setTimeout(() => {
        this.scrollToSelected(this.hours, this.hourList);
        this.scrollToSelected(this.minutes, this.minuteList);
      }, 100);
    }
  }

  selectHour(hour: string) {
    this.hours = hour;
    this.valueHourChange.emit(hour);
    this.valueChange.emit(`${hour}:${this.minutes}`);
    this.scrollToSelected(hour, this.hourList);
  }

  selectMinute(minute: string) {
    this.minutes = minute;
    this.valueMinuteChange.emit(minute);
    this.valueChange.emit(`${this.hours}:${minute}`);
    this.scrollToSelected(minute, this.minuteList);
  }

  handleClickHour(hour: string) {
    this.selectHour(hour);
  }

  handleClickMinute(minute: string) {
    this.selectMinute(minute);
  }

  handleKeyDownHour(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.selectHour(this.hours);
    }
  }

  handleKeyDownMinute(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.selectMinute(this.minutes);
    }
  }

  private addCurrentMinutes() {
    // If the selected minute is not in the minutes array, add it
    if (this.displayMinutes.includes(this.minutes)) {
      return;
    }

    this.displayMinutes.push(this.minutes);
    this.displayMinutes.sort((a, b) => parseInt(a) - parseInt(b));
  }

  private scrollToSelected(value: string, list: ElementRef) {
    const element = list.nativeElement.querySelector(`[aria-selected="true"]`);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }
}

// packages/vue/src/components/time-select/time-select.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted, nextTick } from "vue";
import { Primitive } from "reka-ui";
import { cva, type VariantProps } from "class-variance-authority";

const timeSelectVariants = cva("q-time-select", {
  variants: {},
  defaultVariants: {},
});

export type TimeSelectVariants = VariantProps<typeof timeSelectVariants>;

export interface TimeSelectProps {
  selectedHour?: string;
  selectedMinute?: string;
  hours?: string;
  minutes?: string;
  asChild?: boolean;
  as?: string;
}

const props = withDefaults(defineProps<TimeSelectProps>(), {
  selectedHour: "12",
  selectedMinute: "00",
  hours: "00",
  minutes: "00",
  asChild: false,
  as: "div",
});

const emit = defineEmits<{
  "update:selectedHour": [hour: string];
  "update:selectedMinute": [minute: string];
  "valueChange": [time: string];
  onChange: [time: string];
}>();

// Use selectedHour/Minute if provided, otherwise fall back to hours/minutes
const currentHour = ref(props.selectedHour || props.hours);
const currentMinute = ref(props.selectedMinute || props.minutes);

// Generate hour and minute arrays
const generateDefaultHours = (): string[] => {
  return Array.from({ length: 24 }, (_, i) => i.toString().padStart(2, "0"));
};

const generateDefaultMinutes = (): string[] => {
  return Array.from({ length: 12 }, (_, i) =>
    (i * 5).toString().padStart(2, "0")
  );
};

const displayHours = ref<string[]>(generateDefaultHours());
const displayMinutes = ref<string[]>(generateDefaultMinutes());

// Refs for scroll containers
const hourListRef = ref<HTMLElement | null>(null);
const minuteListRef = ref<HTMLElement | null>(null);

// Watch for prop changes
watch(
  () => props.selectedHour,
  (newHour) => {
    if (newHour !== undefined) {
      currentHour.value = newHour;
      nextTick(() => {
        scrollToSelected(newHour, hourListRef.value);
      });
    }
  }
);

watch(
  () => props.selectedMinute,
  (newMinute) => {
    if (newMinute !== undefined) {
      currentMinute.value = newMinute;
      addCurrentMinute(newMinute);
      nextTick(() => {
        scrollToSelected(newMinute, minuteListRef.value);
      });
    }
  }
);

watch(
  () => props.hours,
  (newHour) => {
    if (newHour && props.selectedHour === undefined) {
      currentHour.value = newHour;
      nextTick(() => {
        scrollToSelected(newHour, hourListRef.value);
      });
    }
  }
);

watch(
  () => props.minutes,
  (newMinute) => {
    if (newMinute && props.selectedMinute === undefined) {
      currentMinute.value = newMinute;
      addCurrentMinute(newMinute);
      nextTick(() => {
        scrollToSelected(newMinute, minuteListRef.value);
      });
    }
  }
);

const addCurrentMinute = (minute: string) => {
  if (!displayMinutes.value.includes(minute)) {
    displayMinutes.value.push(minute);
    displayMinutes.value.sort((a, b) => parseInt(a) - parseInt(b));
  }
};

const scrollToSelected = (value: string, list: HTMLElement | null) => {
  if (!list) return;
  const element = list.querySelector(`[aria-selected="true"]`);
  if (element) {
    element.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }
};

const selectHour = (hour: string) => {
  currentHour.value = hour;
  emit("update:selectedHour", hour);
  const time = `${hour}:${currentMinute.value}`;
  emit("valueChange", time);
  emit("onChange", time);
  nextTick(() => {
    scrollToSelected(hour, hourListRef.value);
  });
};

const selectMinute = (minute: string) => {
  currentMinute.value = minute;
  emit("update:selectedMinute", minute);
  const time = `${currentHour.value}:${minute}`;
  emit("valueChange", time);
  emit("onChange", time);
  nextTick(() => {
    scrollToSelected(minute, minuteListRef.value);
  });
};

const handleClickHour = (hour: string) => {
  selectHour(hour);
};

const handleClickMinute = (minute: string) => {
  selectMinute(minute);
};

const handleKeyDownHour = (event: KeyboardEvent, hour: string) => {
  if (event.key === "Enter") {
    selectHour(hour);
  }
};

const handleKeyDownMinute = (event: KeyboardEvent, minute: string) => {
  if (event.key === "Enter") {
    selectMinute(minute);
  }
};

onMounted(() => {
  addCurrentMinute(currentMinute.value);
  nextTick(() => {
    scrollToSelected(currentHour.value, hourListRef.value);
    scrollToSelected(currentMinute.value, minuteListRef.value);
  });
});

const classes = computed(() => {
  return timeSelectVariants({});
});

const isHourSelected = (hour: string) => hour === currentHour.value;
const isMinuteSelected = (minute: string) => minute === currentMinute.value;
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="classes"
    data-testid="qui-time-select"
    v-bind="$attrs"
  >
    <div
      ref="hourListRef"
      class="time-column"
      data-testid="qui-time-select-hour-list"
    >
      <div
        v-for="hour in displayHours"
        :key="hour"
        data-testid="qui-time-select-hour"
        :class="{ selected: isHourSelected(hour) }"
        :aria-selected="isHourSelected(hour)"
        tabindex="0"
        @click="handleClickHour(hour)"
        @keydown="handleKeyDownHour($event, hour)"
      >
        {{ hour }}
      </div>
    </div>

    <div
      ref="minuteListRef"
      class="time-column"
      data-testid="qui-time-select-minute-list"
    >
      <div
        v-for="minute in displayMinutes"
        :key="minute"
        data-testid="qui-time-select-minute"
        :class="{ selected: isMinuteSelected(minute) }"
        :aria-selected="isMinuteSelected(minute)"
        tabindex="0"
        @click="handleClickMinute(minute)"
        @keydown="handleKeyDownMinute($event, minute)"
      >
        {{ minute }}
      </div>
    </div>
  </Primitive>
</template>

<style scoped>
.q-time-select {
  display: flex;
  border: var(--border-width-default) solid var(--color-border);
  background-color: var(--color-background);
  border-radius: var(--border-radius-lg);
  padding: var(--spacing-4);
  width: var(--spacing-32);
}

.time-column {
  flex: 1;
  overflow-y: auto;
  height: 200px;
  scrollbar-width: thin;
  scrollbar-color: var(--color-border) transparent;
}

.time-column div {
  cursor: pointer;
  border-radius: var(--border-radius-md);
  padding: var(--spacing-2) var(--spacing-3);
  text-align: center;
  font-size: var(--font-size-sm);
}

.time-column div.selected {
  background-color: var(--color-primary);
  color: var(--color-primary-fg);
}

.time-column div:hover:not(.selected) {
  background-color: var(--color-muted);
  color: var(--color-muted-fg);
}

.time-column div:focus-visible {
  outline: none;
  box-shadow: 0 0 0 2px var(--color-ring);
}
</style>
