// packages/angular/src/components/timeline/timeline-title.component.ts
import { Component } from '@angular/core';

@Component({
  selector:
    'h1[qui-timeline-title], h2[qui-timeline-title], h3[qui-timeline-title], h4[qui-timeline-title], h5[qui-timeline-title], h6[qui-timeline-title]',
  standalone: true,
  host: {
    'data-testid': 'qui-timeline-title',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        font-family: var(--font-family-sans);
        font-weight: var(--font-weight-semibold);
        margin: 0;
      }
    `,
  ],
})
export class TimelineTitleComponent {}

// packages/vue/src/components/timeline/timeline-title.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface TimelineTitleProps {
  asChild?: boolean;
  as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
}

const props = withDefaults(defineProps<TimelineTitleProps>(), {
  asChild: false,
  as: "h4",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-timeline-title']"
    data-testid="qui-timeline-title"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: var(--font-family-sans);
  font-weight: var(--font-weight-semibold);
  margin: 0;
}
</style>
