// packages/angular/src/components/timeline/timeline-item.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-timeline-item]',
  standalone: true,
  host: {
    'data-testid': 'qui-timeline-item',
  },
  template: ` <ng-content></ng-content> `,
  styles: [
    `
      :host {
        display: grid;
        grid-template-columns: var(--spacing-8) auto;
      }
    `,
  ],
})
export class TimelineItemComponent {}

// packages/vue/src/components/timeline/timeline-item.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface TimelineItemProps {
  asChild?: boolean;
  as?: "li";
}

const props = withDefaults(defineProps<TimelineItemProps>(), {
  asChild: false,
  as: "li",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-timeline-item']"
    data-testid="qui-timeline-item"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
li {
  display: grid;
  grid-template-columns: var(--spacing-8) auto;
}
</style>
