// packages/vue/src/components/empty-state/empty-state-action-group.vue
<script setup lang="ts">
import { Primitive } from 'reka-ui'

export interface EmptyStateActionGroupProps {
  asChild?: boolean
  as?: string
}

const props = withDefaults(defineProps<EmptyStateActionGroupProps>(), {
  asChild: false,
  as: 'div'
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="['q-empty-state-action-group']"
    data-testid="qui-empty-state-action-group"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
.q-empty-state-action-group {
  display: flex;
  gap: var(--spacing-2);
}

.q-empty-state-action-group :deep(*) {
  width: 100%;
}
</style>

// packages/angular/src/components/empty-state/empty-state-action-group.component.ts
import { Component } from '@angular/core';

@Component({
  selector: '[qui-empty-state-action-group]',
  host: {
    'data-testid': 'qui-empty-state-action-group',
  },
  template: '<ng-content></ng-content>',
  styles: [
    `
      /* stylelint-disable selector-pseudo-element-no-unknown */
      :host {
        display: flex;
        gap: var(--spacing-2);
      }

      :host ::ng-deep * {
        width: 100%;
      }
    `,
  ],
  standalone: true,
})
export class EmptyStateActionGroupComponent {}
