// packages/angular/src/components/call-to-action/cta.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'div[qui-cta]',
  standalone: true,
  imports: [CommonModule],
  host: {
    'data-testid': 'cta',
  },
  template: `<ng-content></ng-content>`,
  styles: [
    `
      :host {
        position: relative;
        padding: var(--spacing-16) 0;
        width: 100%;
      }
    `,
  ],
})
export class CTAComponent {}

// packages/vue/src/components/call-to-action/cta.vue
<script setup lang="ts">
import { Primitive } from "reka-ui";

export interface CTAProps {
  asChild?: boolean;
  as?: "div";
}

const props = withDefaults(defineProps<CTAProps>(), {
  asChild: false,
  as: "div",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    class="q-cta"
    data-testid="qui-cta"
    v-bind="$attrs"
  >
    <slot />
  </Primitive>
</template>

<style scoped>
div {
  position: relative;
  padding: var(--spacing-16) 0;
  width: 100%;
}
</style>
